### ISSUE TITLE
Create Course Page

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/edu-client#1]
Full Course page: 
![My Courses](https://user-images.githubusercontent.com/48255244/110598690-0b5c0180-81a8-11eb-9aac-ed88b1419b7a.png)

Use Material UI  for creating components:
Material-ui: https://material-ui.com/
Ionic: https://ionicframework.com/docs/react

**Comment by AdityaTeltia** [comment]
I would like to work on this ! We have to build the UI as shown in the image right ? Can you give me more details about this issue

**Comment by rizwan2000rm** [comment]
Also @Abhishek-kumar09 I think there should only be a single card component right ? Just to maintain a consistency over the website. One of the card component here and in #5 looks the same. So we don't need two people working on the same card, one can use the component of other directly.

**Comment by Abhishek-kumar09** [comment]
>  One of the card component here and in #5 looks the same. So we don't need two people working on the same card, one can use the component of other directly.

Yes

**Comment by AdityaTeltia** [comment]
Ok got it can you assign me this issue

**Comment by AdityaTeltia** [comment]
What is this ionic framework link for ?

**Comment by Abhishek-kumar09** [comment]
We are creating app with ionic framework to port the app in Mobile and iOS devices

**Comment by AdityaTeltia** [comment]
Oh ok ! Do I have to do something in this issue regarding that or I just have to create this UI in react ?

**Comment by Abhishek-kumar09** [comment]
Create UI in react for now

**Comment by AdityaTeltia** [comment]
Ok ! Sure Thankyou

**Comment by Abhishek-kumar09** [comment]
>  I have some knowledge of Ionic and Capacitor too.

Great, @Striver08. But this issue is already taken by Aditya, We will be creating new issues very soon.

**Comment by Striver08** [comment]
Okay, Waiting for them.

> > I have some knowledge of Ionic and Capacitor too.
> 
> Great, @Striver08. But this issue is already taken by Aditya, We will be creating new issues very soon.
