### ISSUE TITLE
[Bug] Env variable in authService Api key not matching with key defined in .env.example 

### ISSUE THREAD

**Issue by NeelParihar** [codeforcauseorg/edu-client#104]
## Describe the bug

In services/authService.js  the env key for firebase api key is **REACT_APP_FIREBASE_API_KEY** but in .env.example the key is defined as **REACT_APP_API_KEY**, this does not allow the application to connect with firebase.

## To Reproduce

1. Clone the project, install all the dependencies.
2. copy .env.example to .env file, put your firebase credentials.
3. Run the app using npm start.
4. see browser console, which gives a error for api key not valid.

<img width="1280" alt="Screenshot 2021-03-16 at 12 54 01 PM" src="https://user-images.githubusercontent.com/51474217/111271184-dd1e6c00-8656-11eb-8159-8a0c774945d8.png">

## Expected behavior

After setting up the project and setting up the .env file it should be able to connect to firebase when the app is running.

<img width="1279" alt="Screenshot 2021-03-16 at 12 56 41 PM" src="https://user-images.githubusercontent.com/51474217/111271473-3c7c7c00-8657-11eb-8b53-e1854ee6bac7.png">

## Logs

<img width="465" alt="Screenshot 2021-03-16 at 12 52 29 PM" src="https://user-images.githubusercontent.com/51474217/111271024-a8121980-8656-11eb-8571-e904b50dd6dd.png">

## Environment

- OS: MacOS Catalina.
- Browser: Chrome

**Comment by Anurag5086** [comment]
@NeelParihar I made a PR for this issue.

**Comment by san0808** [comment]
has thr pr been not merged yet because i am still getting the problem @Anurag5086

**Comment by Anurag5086** [comment]
@san0808 Not yet. Please merge the PR #105 @Abhishek-kumar09 @rajatgupta24 .

**Comment by Abhishek-kumar09** [comment]
Fix is merged.
