### ISSUE TITLE
docs: Include license section in Readme

### ISSUE THREAD

**Issue by Amulya-coder** [codeforcauseorg/edu-client#112]
## Is your feature request related to a problem? Please describe.
Mention about the license under which the organization follows in the readme separately

## Describe the solution you'd like
Add license section in the readme this is a great way to encourage more free, open-source code.

## Additional context
Here's the link: https://github.com/codeforcauseorg/edu-client/blob/main/LICENSE

**Comment by Amulya-coder** [comment]
@Abhishek-kumar09  it's a few minutes issue I would like to take this.

**Comment by Abhishek-kumar09** [comment]
its already there in the readme just above prerequisites.

I am closing this issue, feel free to open it if needed.
