### ISSUE TITLE
Text wrap in bottom Nav actions.

### ISSUE THREAD

**Issue by Abhijay007** [codeforcauseorg/edu-client#114]
## Describe the bug

In the contents of the bottom nav, the text for the "My class" label gets wrapped for smaller android screens when the user switches between contents of the bottom nav, which leads icon for my class uplifted a bit higher (seems like overflowing)  as compared to other icons which sets a bad UI example.

## To Reproduce

1.swipe between the contents of the bottom nav and stay on my class label

currently on the web:
![before-bug](https://user-images.githubusercontent.com/64387054/111519291-f1f51f80-877c-11eb-847d-8a29b9265a3a.gif)

![bug-bottonNav](https://user-images.githubusercontent.com/64387054/111519455-1fda6400-877d-11eb-94de-947251c80ae7.PNG)

## Expected behavior

![after-bug](https://user-images.githubusercontent.com/64387054/111519176-d38f2400-877c-11eb-96ec-79e7208e4780.gif)

icon for "my class" label should be even with other labels means behave same as other labels no text wrap 

## Environment (please complete the following information):

- OS: windows
- Browser: chrome

**Comment by Abhijay007** [comment]
@Abhishek-kumar09 can i work on this ?

**Comment by rajatgupta24** [comment]
@Abhijay007 I reported this earlier & just create a PR regarding this.

**Comment by Abhijay007** [comment]
Nice!! 😁 as you opened a PR for this issue but from next time At least
take mentor's permission before opening a PR . At least give mentors some
time to review issue once and approve it!!

**Comment by rajatgupta24** [comment]
@Abhijay007, I reported this earlier #27 and was assigned

**Comment by Abhijay007** [comment]
Ok

**Comment by Abhijay007** [comment]
bug still exists for smaller screens: 

![bug-remains](https://user-images.githubusercontent.com/64387054/111761916-6edfe080-88c6-11eb-90fd-1fefeddc56ce.gif)

**Comment by Abhijay007** [comment]
@Abhishek-kumar09  can I work on this?
