### ISSUE TITLE
Back to top button

### ISSUE THREAD

**Issue by Harshal0902** [codeforcauseorg/edu-client#117]
## Is your feature request related to a problem? Please describe.

Adding a back to top button.

## Describe the solution you'd like

A button to return to the top of the page allows the user to quickly return to the top of the page without making too much effort.

## Additional context

NA

**Comment by Harshal0902** [comment]
@Abhishek-kumar09 can I work on this issue?

**Comment by PrashubhAtri** [comment]
Can i Work on this @Abhishek-kumar09

**Comment by Harshal0902** [comment]
@KeenWarrior ig we supposed to get issue assigned first, then work on it?

**Comment by Abhishek-kumar09** [comment]
Yes @Harshal0902 sorry if you had already started working on it and the issue is merged. Yes, issue need to be assigned first but maybe due to this volume of PR we missed your comment and merged it. Sorry for that.
