### ISSUE TITLE
UI Bug in Header Item Box section 

### ISSUE THREAD

**Issue by Abhijay007** [codeforcauseorg/edu-client#121]
## Describe the bug

In the header item box section when the user opens the application in smaller devices(width between 280 to 320px) like I phone 5, galaxy fold, etc. then the box content gets overflowed and makes UI inconsistent as it takes more space than required on the right side of the app.

## To Reproduce

1. open chrome inspect element 
2. open mobile view 
3. switch between different devices which has smaller screen size (for ex: I phone 5)

## Expected behavior

make it as it looks in other devices mean remove excess space from the right side and prevent it from the overflow 

## Environment (please complete the following information):

- OS: windows 
- Browser: chrome

## Additional context

![UI-bug](https://user-images.githubusercontent.com/64387054/111819774-c140f180-8906-11eb-8543-2be9fc26841e.gif)
![bug](https://user-images.githubusercontent.com/64387054/111820073-111fb880-8907-11eb-90a7-1d4b19ca63f1.PNG)

**Comment by poojadas07** [comment]
@Abhishek-kumar09 Yeahh, I also got the same problem. Can I work on this issue?

**Comment by poojadas07** [comment]
![Capture1](https://user-images.githubusercontent.com/66192403/111891461-58966980-8a19-11eb-9aaf-90bb189708f3.PNG)
@Abhijay007 Please check.
Overflowed problem is removed all the screen size.
