### ISSUE TITLE
Generate Design for Profile Page

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/edu-client#128]
## Is your feature request related to a problem? Please describe.

A profile page design is needed to showcase the profile.

## Describe the solution you'd like

A figma based profile page, where we can collaborate.

**Comment by Abhishek-kumar09** [comment]
@mindninjaX, @Shitiz-aggarwal

Do you want to work on this?

**Comment by SHITIZ-AGGARWAL** [comment]
@Abhishek-kumar09 yes for sure

**Comment by SHITIZ-AGGARWAL** [comment]
@Abhishek-kumar09 If there are any other designing issues , I would love to take them .

**Comment by Abhishek-kumar09** [comment]
Lovely, I just got the update that someone is making profile page design. You all can collaborate with each other once confirmed.

**Comment by adarsh-technocrat** [comment]
Hey @Abhishek-kumar09  can you please assign this to me, I and @SHITIZ-AGGARWAL  will collaborate and work on this  :)

**Comment by adarsh-technocrat** [comment]
Hey, @Abhishek-kumar09  just ended up working on the Profile Screen UI please have a look :)

<img src="https://user-images.githubusercontent.com/47661086/112107401-e8ccde00-8bd4-11eb-8903-e2a978f6f6fd.png"/>

Please Suggest if any sort of change is required.

/Cc @KeenWarrior

**Comment by KeenWarrior** [comment]
LGTM

**Comment by adarsh-technocrat** [comment]
> LGTM

Hey @KeenWarrior ,@Abhishek-kumar09    Should I land PR for this ?

**Comment by Abhishek-kumar09** [comment]
Yes you can start making pull request.
We are using material-ui, its very easy and responsive.

**Comment by adarsh-technocrat** [comment]
> Yes you can start making pull request.
> We are using material-ui, its very easy and responsive.

Sure thing @Abhishek-kumar09! I'll land PR soon for this issue :)

**Comment by Abhijay007** [comment]
> Hey, @Abhishek-kumar09 just ended up working on the Profile Screen UI please have a look :)
> 
> ![](https://user-images.githubusercontent.com/47661086/112107401-e8ccde00-8bd4-11eb-8903-e2a978f6f6fd.png)

UI looks good @adarsh-technocrat 👍
