### ISSUE TITLE
Create Student Dashboard Design

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/edu-client#135]
A student dashboard for seeing the personalised information for the students
Student Dashboard
- Students can see their different progress in courses
- Students can give the link to their github profile, linked profile, leetcode profile, codechef, codeforces profile and their progress could be fetched from there
- They can see the active assignments, pending assignments
- Could request doubt support from TA using calendly invite
- They can apply for open positions within the organisation

**Comment by AvineshTripathi** [comment]
@Abhishek-kumar09 can i work on this ?

**Comment by adarsh-technocrat** [comment]
> @Abhishek-kumar09 can i work on this ?

Hey, @AvineshTripathi I have some ideas related to student dashboard design I would love to share if you don't mind :)

**Comment by AvineshTripathi** [comment]
@adarsh-technocrat ya sure infact we can work together m just a newbie so I would be really happy if we work toagther

**Comment by adarsh-technocrat** [comment]
> @adarsh-technocrat ya sure infact we can work together m just a newbie so I would be really happy if we work toagther

Great @AvineshTripathi  can you please tell me which tool you using?

**Comment by AvineshTripathi** [comment]
@adarsh-technocrat  its avineshtripathi1@gmail.com

**Comment by adarsh-technocrat** [comment]
Hey @Abhishek-kumar09  can we both assign to this issue?

**Comment by adarsh-technocrat** [comment]
> * Students can give the link to their github profile, linked profile, leetcode profile, codechef, codeforces profile and their progress could be fetched from there

Hey, @Abhishek-kumar09  can you please describe this section `progress could be fetched ` according to my understanding is it fetching the statistic of a student from these various platforms using their respective **`API's`**?

**Comment by Abhishek-kumar09** [comment]
> Hey, @Abhishek-kumar09 can you please describe this section progress could be fetched according to my understanding is it fetching the statistic of a student from these various platforms using their respective API's?

Yes

**Comment by adarsh-technocrat** [comment]
Hello, @Abhishek-kumar09   just wanted to know something about the  `Jobs Openings section ` is there will be any sort of detail page that will describe the job description,  required skills, etc, and also want to know how they will be applying for the job position is they will be sharing just a resume or filling a job application form which will include the basic requirements.

As the Jobs Openings section will be a completely different page, I am just adding a button on the dashboard that will navigate to the jobs opening page. I have  added a few points below according to my vision:

1. List of Job openings 
2. Jobs can be filtered according to  `internships`, `full-time`, `in-office ` and `remote`,
3.  Detail Job Page which will describe the particular job and related information
4.  Appling for the job by filling out the application
5. Application status section which will tell the status of the application.

 @Abhishek-kumar09  if you agree with the flow then I will go for adding these things! would love to hear your thoughts on this =)

**Comment by Abhishek-kumar09** [comment]
Don't worry more about job opening design page, we will be redirecting it to our website where we have some design for it.

**Comment by adarsh-technocrat** [comment]
> Don't worry more about job opening design page, we will be redirecting it to our website where we have some design for it.
Sure @Abhishek-kumar09  :)

**Comment by adarsh-technocrat** [comment]
Hello, @Abhishek-kumar09 @KeenWarrior 👋  just ended up working on the Student Dashboard Design Section here is the Figma link  https://www.figma.com/file/N8kDl83jL73AZ8XZIbF6Xn/CFC-Student-Dashboard?node-id=0%3A1  would love to hear your thoughts on this!

**Comment by adarsh-technocrat** [comment]
if UI gets approval should I go for making the PR and bit confused about the Dashboard Screen placement where it can be placed?

**Comment by Abhishek-kumar09** [comment]
It can be a new page, the profile page would have the option to go to your dashboard.

**Comment by adarsh-technocrat** [comment]
> It can be a new page, the profile page would have the option to go to your dashboard.

Sure thing @Abhishek-kumar09  Hey @AvineshTripathi   you can go making pr for Header Section as we discussed earlier right! I will follow up with your  PR for creating a middle section ping me here if you have any doubts :)
