### ISSUE TITLE
Create Design for Peer Discussion page

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/edu-client#136]
A peer discussion page is needed where

- Where peers can talk with each other in form of blogs, resolve each others doubts etc
- They can give course feedback
- The healthy competition like solving problems etc could be made here
- People can share notes, papers, their thoughts and forums in the form of threads

**Comment by poojadas07** [comment]
@Abhishek-kumar09 I want to work on this page. Please assign to me

**Comment by adarsh-technocrat** [comment]
> @Abhishek-kumar09 I want to work on this page. Please assign to me

Hey, @poojadas07  if you need any sort of help from my side designing the Page in Figma or adobe xd just ping me out.
always ready help :p

**Comment by san0808** [comment]
@Abhishek-kumar09  i wanted ask is this not the same think i had asked in issue  #132 and you assigned it to me i believe the idea is the please tell me if what i am thinking is wrong

**Comment by Abhishek-kumar09** [comment]
@san0808
I think that was a chat section you were talking about, and that could be made like a chat interface that will be more personalised.

This page more resembles to blogging page, forums and course discussion page etc.

**Comment by poojadas07** [comment]
> > @Abhishek-kumar09 I want to work on this page. Please assign to me
> 
> Hey, @poojadas07 if you need any sort of help from my side in designing the Page in Figma or adobe xd just ping me out.
> always ready help :p

Okay
