### ISSUE TITLE
Logout Button Alignment Issue

### ISSUE THREAD

**Issue by Kunal-2001** [codeforcauseorg/edu-client#14]
![Logout_Issue](https://user-images.githubusercontent.com/61347506/110737947-6cd9aa00-8254-11eb-82fd-6770db94650e.png)
### Issue
By Clicking on profile picture logout button pops up, but the allignment of this button is overlapping with the profile photo
### Fix
The logout button should have some margin on the top

**Can you please assign this issue so that I could fix this
Thank you**

**Comment by harshshaw** [comment]
can i work on this?

**Comment by Grumpyyash** [comment]
I think the login feature has been removed for now in the codebase @Kunal-2001

**Comment by KeenWarrior** [comment]
These features are to be shifted to the profile page. You can put a logout button on ProfileView.

Use Button from Material-UI

**Comment by Kunal-2001** [comment]
@KeenWarrior Is there any template sample for profile view as for now the authentication feature is removed from the app ??

**Comment by Striver08** [comment]
I would like to work on this issue, @KeenWarrior You can assign the same to me.

**Comment by NishcheyBhutani** [comment]
I am a newbie....I would like to work on this issue....please assign it to me!? @KeenWarrior @Kunal-2001

**Comment by NishcheyBhutani** [comment]
?? @Kunal-2001 @KeenWarrior

**Comment by Kunal-2001** [comment]
@NishcheyBhutani Actually I am working on this

**Comment by NishcheyBhutani** [comment]
oh alright! my bad

**Comment by Abhishek-kumar09** [comment]
Hi @Kunal-2001 I guess it is not needed anymore since we would be having only bottomnavbar in most of the screens. We would be needing some screens with appbar but current appbar with minimal changes would suffice the need. 

Thank you for opening the issue. 
I am closing it for now. But in any case if you need to open it again feel free to do so.
