### ISSUE TITLE
Fix: continue learning cards

### ISSUE THREAD

**Issue by rajatgupta24** [codeforcauseorg/edu-client#140]
Hi guys,
It's hard to scroll through the continue learning section when we've a lot of courses going on.

I think the cards in continue learning section can be better is they are in horizontal scroll. 

It'll make it short and mobile friendly.
*I can make the changes in my PR #85 because it contains similar functionality.*

**Comment by rajatgupta24** [comment]
@Abhishek-kumar09 can I start working on it.

**Comment by naveen8801** [comment]
Hii @rajatgupta24  , i wanna work on it ,  can you help me in getting started :-)

**Comment by rajatgupta24** [comment]
Hi @naveen8801 👋🏻, sure you can, first join our discord channel and setup the repo locally and go through the files in src folder
If you need any help just ask on discord and wait till issue is assigned to you 😇

**Comment by naveen8801** [comment]
Thanks  @rajatgupta24  :-)

**Comment by rajatgupta24** [comment]
Hi @naveen8801, how's this going?

**Comment by naveen8801** [comment]
Hii @rajatgupta24 , i have successfully setup this repo locally and code base looks familiar to me , currently i am spending time in understanding different components involved in this application  :-)

**Comment by rajatgupta24** [comment]
Great start :partying_face:, and what about the current issue, are you still doing it?

**Comment by naveen8801** [comment]
ya , i am working in it . should i directly submit a PR or wait for someone assign this issue to me ?

**Comment by rajatgupta24** [comment]
It has been a while so you should just submit a PR now

**Comment by naveen8801** [comment]
Thanks @rajatgupta24 :-)

**Comment by naveen8801** [comment]
@rajatgupta24  , i am facing some problem while solving this , actually i am able to make that list vertically scrollable not horizontally , can you help me ?
