### ISSUE TITLE
Fix: Typography font sizes

### ISSUE THREAD

**Issue by faisaljamil25** [codeforcauseorg/edu-client#141]
I think the typography font sizes are too small to be able to read properly. Also, there is no regular increase in font size from h6 to h1, making it difficult for developers to follow a pattern.
You can check here the typography configuration: [https://github.com/codeforcauseorg/edu-client/blob/main/src/theme/typography.js](url)

**Comment by faisaljamil25** [comment]
@Abhishek-kumar09 can I work on this?

**Comment by Abhishek-kumar09** [comment]
I have asked this to @adarsh-technocrat, but if you want you can work on it.

**Comment by faisaljamil25** [comment]
Yeah, sure I'm working on it.
