### ISSUE TITLE
There must be some margin / padding on the top of home and my classes page.

### ISSUE THREAD

**Issue by himanshu211raj** [codeforcauseorg/edu-client#148]
see the below images for understanding the requirements properly.
![my classes](https://user-images.githubusercontent.com/55490277/112709457-dd80f780-8edf-11eb-9147-0836206d0ea1.png)
![home](https://user-images.githubusercontent.com/55490277/112709458-e376d880-8edf-11eb-97ab-575c3bf000ed.png)

**Comment by sandyabhi** [comment]
Hey @himanshu211raj  I would like to work on it

**Comment by sandyabhi** [comment]
How about 10px margin ?
![CFC](https://user-images.githubusercontent.com/75850277/112716633-7bd78200-8f0d-11eb-8a6d-2b2ed839fc7e.png)

**Comment by himanshu211raj** [comment]
> How about 10px margin ?
> ![CFC](https://user-images.githubusercontent.com/75850277/112716633-7bd78200-8f0d-11eb-8a6d-2b2ed839fc7e.png)

It's fine @KeenWarrior @Abhishek-kumar09 @kunal-kushwaha kindly review it so it can be applied.

**Comment by Abhishek-kumar09** [comment]
This issue can't be approved, sorry.
We can't add just anything without prebuilt design.

I am closing this issue so as to manage open issues better.

Feel free to open it if you need it anyway.
