### ISSUE TITLE
Video Player Consistency

### ISSUE THREAD

**Issue by rizwan2000rm** [codeforcauseorg/edu-client#149]
## Describe the bug

There are currently two different video player packages. video-react and react-player. I think we only need one npm package which can be used for every purpose. React Player seems to be a better option as it is still being maintained.

## Additional context

If we agree on either package, we should remove the other package and use same player everywhere.

**Comment by rizwan2000rm** [comment]
@KeenWarrior @Abhishek-kumar09 ping!

**Comment by Abhishek-kumar09** [comment]
Do you want to work on it?

**Comment by rizwan2000rm** [comment]
@rizwan2000rm Yeah sure. I will work on it.
