### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by Siddhant-K-code** [codeforcauseorg/edu-client#15]
- [ ] Basic of Fork,Clone & hitting a PR
- [ ] Setting up the Project Locally
- [ ] Code of Conduct
- [ ] Contributing Rules/Style (same as #13)

**Comment by kaiwalyakoparkar** [comment]
Hey @Siddhant-K-code, I would like to work on this issue. Could you please guide me?

**Comment by Siddhant-K-code** [comment]
## Basic of Fork, Clone & hitting a PR

It is pretty basic, you just have to add steps for a beginner-friendly ( initial steps you did to fork, clone into your system, creating a PR, upstream commands for updating forked repo with the original repo. ) with Screenshots. 

## Setting up the Project Locally

 Yarn Commands we ran to install dependencies and running it on localhost:

`yarn install`

if you have to face any `ERR regarding ESOCKETTIMEOUT`

run: 
`yarn install --network-timeout 500000`

after completion, run `yarn start` to run it on `localhost:3000`


***you just have to document the above info with proper description and easy to understand manner***

**Comment by kaiwalyakoparkar** [comment]
does this project work with npm so that I can add that too?

**Comment by kaiwalyakoparkar** [comment]
Please assign this issue to me. I would like to work on this.

**Comment by Siddhant-K-code** [comment]
> does this project work with npm so that I can add that too?

Just Go Through the Project Once.

And, Remember this thing for all Similar Tech Stack Projects: 

```
Check if the project has `yarn.lock` (installed with yarn) or `package-lock.json` (installed with npm)
```

**Comment by ritvij14** [comment]
@Siddhant-K-code isn't this just what  #13 asks to do? I can make the issue more descriptive if you want.

**Comment by ritvij14** [comment]
@Siddhant-K-code I can take up the `Contributing.md` part, and then I will close #13 which asks for the same task. Can you assign that part to me? (You could tag me in the issue description for making that doc, so that way we know who is working on what part)

**Comment by Siddhant-K-code** [comment]
@ritvij14 made the changes, will add your name beside it when you will get assigned by maintainers.

**Comment by kaiwalyakoparkar** [comment]
Hey @Siddhant-K-code , I tried to run the project on my local machine using npm as well as yarn for yarn it is showing the error as follow:
yarn run v1.22.10
$ react-scripts start
'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.

**Comment by kaiwalyakoparkar** [comment]
Ok I am just setting up the project on my local machine. I will get back to you as soon as I finish exploring the project

**Comment by kaiwalyakoparkar** [comment]
There was a problem in package.json in react scripts:
  "react-scripts": "^4.0.3", was written as   "react-scripts": "4.0.3", that gave error while running in local machine

**Comment by kaiwalyakoparkar** [comment]
Hey I set up the project in my local environment. I tried both npm and yarn to run the project in localhost:3000. Both are working super fine. both yarn.lock and package-lock.json are present in the project. What should I do next? 
Also,
There was a problem in package.json in react scripts:
"react-scripts": "^4.0.3", was written as "react-scripts": "4.0.3", that gave error while running in local machine

**Comment by kaiwalyakoparkar** [comment]
Please assign this to me I am super excited to do all 4 tasks

**Comment by Siddhant-K-code** [comment]
> Hey I set up the project in my local environment. I tried both npm and yarn to run the project in localhost:3000. Both are working super fine. both yarn.lock and package-lock.json are present in the project. What should I do next?
> Also,
> There was a problem in package.json in react scripts:
> "react-scripts": "^4.0.3", was written as "react-scripts": "4.0.3", that gave error while running in local machine

what was the error?

**Comment by kaiwalyakoparkar** [comment]
It was a syntax error for version or react scripts

**Comment by kaiwalyakoparkar** [comment]
I resolved that by npm install react-scripts command which also update the pacage-lock.json file

**Comment by Siddhant-K-code** [comment]
> I resolved that by npm install react-scripts command which also updated the package-lock.json file

yeah, it's okay. also, did you face ESOCKETTIMEOUT err ?

**Comment by kaiwalyakoparkar** [comment]
after that, it runs on localhost server

**Comment by kaiwalyakoparkar** [comment]
> > I resolved that by npm install react-scripts command which also updated the package-lock.json file
> 
> yeah, it's okay. also, did you face ESOCKETTIMEOUT err ?

No

**Comment by Siddhant-K-code** [comment]
> I resolved that by npm install react-scripts command which also updated the package-lock.json file

your `yarn.lock` should also get updated!! will create a PR for the same.

**Comment by kaiwalyakoparkar** [comment]
> > > I resolved that by npm install react-scripts command which also updated the package-lock.json file
> > 
> > 
> > yeah, it's okay. also, did you face ESOCKETTIMEOUT err ?
> 
> No

But we can add steps to resolve it in the documentation section

**Comment by kaiwalyakoparkar** [comment]
> > I resolved that by npm install react-scripts command which also updated the package-lock.json file
> 
> your `yarn.lock` should also get updated!! will create a PR for the same.

Yes it does gets updated when we run yarn install react scripts

**Comment by kaiwalyakoparkar** [comment]
https://github.com/kaiwalyakoparkar/edu-client/tree/documentation

**Comment by kaiwalyakoparkar** [comment]
I have also added Contributing.md, Code-of-conduct.md and all you asked. Also I have made changes which fixed the previous errors

**Comment by Abhishek-kumar09** [comment]
> I have also added Contributing.md, Code-of-conduct.md and all you asked. Also I have made changes which fixed the previous errors

Please create a PR, We will discuss the rest there.

**Comment by kaiwalyakoparkar** [comment]
ok

**Comment by helloCodingEra** [comment]
@Abhishek-kumar09 there are still some mistakes in the documentation which i want to correct it can i do that ??
and also guide me with it
