### ISSUE TITLE
# feature request =>  Adding the "Take the notes " feature while attending the lectures .

### ISSUE THREAD

**Issue by ayush19030** [codeforcauseorg/edu-client#152]
## Describe the solution you'd like

While viewing the lecture the user can be provided with space where he can 
take note of the important points. 
The notes will be saved for future reference.

**Comment by sakshi-choudhary** [comment]
I would like to work on this. Could you please assign this to me @Abhishek-kumar09

**Comment by ayush19030** [comment]
@sakshi-choudhary  I want to work on this , was just waiting for the approval of @Abhishek-kumar09

**Comment by sakshi-choudhary** [comment]
Is someone still working on this? I would like to work on this @Abhishek-kumar09  @vasudev19126

**Comment by vasudev19126** [comment]
@sakshi-choudhary Yes, you can work on this. I think he is not active anymore.

**Comment by adarsh-technocrat** [comment]
Hey, @Abhishek-kumar09  we can close this issue!
