### ISSUE TITLE
# feature request => Course Progress graph on Profile Section

### ISSUE THREAD

**Issue by ayush19030** [codeforcauseorg/edu-client#153]
## Describe the solution you'd like

On the profile page, a progress section can be introduced. 
The progress Section contains the graph keeping the track of progress. 
The current progress can be compared to the average progress graph. 
We can also introduce the leaderboard depending on the number of users taking a particular course. 

![img1](https://user-images.githubusercontent.com/55682038/112731271-3f7f4280-8f5c-11eb-8ff3-e114b732b7ae.JPG)

**Comment by Abhishek-kumar09** [comment]
Please fill in the required details, follow Issue template and make title short

**Comment by ayush19030** [comment]
@Abhishek-kumar09  I have updated all the proposed features in the desired formats, Kindly have a look at them.

**Comment by ayush19030** [comment]
@Abhishek-kumar09  Can you please provide your consent over this .

**Comment by Abhishek-kumar09** [comment]
That sounds good but how are you thinking to implement this?

**Comment by rajatgupta24** [comment]
Hey @ayush19030 and @Abhishek-kumar09, instead of showing it on the profile page I think the more section of the course itself is a better place for this and this can be done by comparing the result of the quizzes in between the course compare your result with the average, highest, or your friend (who is attending the course).

**Comment by ayush19030** [comment]
@rajatgupta24 Actually I was creating a button in a Profile Page and then navigating into the user progress page.

**Comment by Abhijay007** [comment]
@ayush19030  you can close this issue, as it was resolved in this PR (#237).
