### ISSUE TITLE
My Courses should have a list of courses 

### ISSUE THREAD

**Issue by sakshi-choudhary** [codeforcauseorg/edu-client#159]
## Is your feature request related to a problem? Please describe.

Currently, my courses page is designed as such if the user has enrolled in only 1 course.

## Describe the solution you'd like

My Courses should have a list of all the courses bought by the student, and after clicking on a particular course, the video and chapters of the course will show up.

**Comment by naveen8801** [comment]
Hi @sakshi-choudhary  ,  @Abhishek-kumar09  , I'd like to work on it , can you assign it to me :-)

**Comment by sakshi-choudhary** [comment]
@naveen8801 Actually, I wanted to work on this, was waiting for @Abhishek-kumar09 's reply.

**Comment by sakshi-choudhary** [comment]
@Abhishek-kumar09 Could you please assign this to me?

**Comment by sakshi-choudhary** [comment]
I have worked on this issue. Please check the PR #170 @Abhishek-kumar09

**Comment by Abhijay007** [comment]
I think this issue is resolved you may close this now @sakshi-choudhary as your PR Succesful get merged 👍
