### ISSUE TITLE
Events page 

### ISSUE THREAD

**Issue by harshshaw** [codeforcauseorg/edu-client#16]
For now the Events page is showing no info so we can add 
1.  A carousel for Events pictures 
2. Image cards for Events with basic info
3. Contact area

**Comment by Siddhant-K-code** [comment]
Yes, I guess we should create at least the major outlines on every page like `./events`, `./campusLeaders`

**Comment by harshshaw** [comment]
@Siddhant-K-code  yes we can add routes to it please provide a template or design if u have to work accordingly

**Comment by KeenWarrior** [comment]
Those pages are not part of the plan and were left there for some testing reason. Have been removed now.
