### ISSUE TITLE
feature request=>mentor profile section

### ISSUE THREAD

**Issue by AnanyaNegi** [codeforcauseorg/edu-client#165]
## Is your feature request related to a problem? Please describe.

The courses can use a mentor description section in which the user can familiarise themselves with the basic intro of speakers/mentors. This will lead to user assurance and a better understanding of the course before buying it.

## Describe the solution you'd like

A mentor section. When the user clicks on the mentor name, he/she will be redirected to this section.

**Comment by AnanyaNegi** [comment]
@Abhishek-kumar09 I would like to contribute to this issue, Pls assign it to me.

**Comment by Abhijay007** [comment]
@Abhishek-kumar09 can I work on this?

**Comment by vasudev19126** [comment]
@Abhijay007 yeah, you can work on this.
