### ISSUE TITLE
Course Description Page

### ISSUE THREAD

**Issue by poojadas07** [codeforcauseorg/edu-client#168]
## Is your feature request related to a problem? Please describe.

When we click on a course card , it will take us to new page which contains the details of that particular course like course name , small description of the course , price , author details , adding to wishlist option , duration of course , etc.

## Describe the solution you'd like

Course description page contains all the information of the particular course.

@KeenWarrior @Abhishek-kumar09  Can I work on this ?

**Comment by Abhijay007** [comment]
@poojadas07  in think it is already solved in issue no: #92

**Comment by poojadas07** [comment]
> @poojadas07 in think it was already solved in issue no: #92

Ohhkkk....I missed that.
