### ISSUE TITLE
Empty about-us page 

### ISSUE THREAD

**Issue by rajatgupta24** [codeforcauseorg/edu-client#171]
## Describe the bug
On the Homepage continue learning section I can see a horizontal scrollbar on cards
I can't see anything on the about us page and can't render faqs pages
there is a console.log on the privacy page

## To Reproduce

1. You can see the scrollbar on the homepage
2. try to go to /about 
3. try to go to /faqs
4. see in the console after going to /privacy

## Expected behavior

- There shouldn't be a scrollbar
- All pages should render properly
- There shouldn't any console.log  

## Environment (please complete the following information):

- OS: Linux: Ubuntu
- Browser: Firefox

**Comment by rajatgupta24** [comment]
Hi @Abhishek-kumar09, I already made all the required changes should I open a PR.

**Comment by Abhishek-kumar09** [comment]
yes, for sure
