### ISSUE TITLE
Improve Some Spelling and Spaces in contributing.md

### ISSUE THREAD

**Issue by rohank2502** [codeforcauseorg/edu-client#173]
![Screenshot 2021-03-30 194010](https://user-images.githubusercontent.com/76584243/113003109-09c29f80-9190-11eb-9527-db6cb20b993e.png)

Space before new

**Comment by suubh** [comment]
Locale is fine . It indicates a place ,environment  or settings where things happen .

**Comment by rohank2502** [comment]
> 
> 
> Locale is fine . It indicates a place ,environment or settings where things happen .

oo i was not knowing about this thanks !
