### ISSUE TITLE
Social Sharing of the App

### ISSUE THREAD

**Issue by poojadas07** [codeforcauseorg/edu-client#178]
## Is your feature request related to a problem? Please describe.

We can share this mobile app with others via whatsapp ,  twitter , mail, etc.

## Describe the solution you'd like

Add social sharing with this application.

@KeenWarrior @Abhishek-kumar09 Can I work on this ?

**Comment by Abhishek-kumar09** [comment]
Is it same as https://github.com/codeforcauseorg/edu-client/issues/179

**Comment by poojadas07** [comment]
> Is it same as #179

Yes ....But I opened this issue earlier.

**Comment by Abhishek-kumar09** [comment]
Oh sorry, I always request everyone to see the issues if already opened before opening a new one.

I think she has started working, nevermind your contribution counts too.

**Comment by sakshi-choudhary** [comment]
I'm sorry, @poojadas07 You can work on it
