### ISSUE TITLE
#Feature Request=> Referral Option 

### ISSUE THREAD

**Issue by sakshi-choudhary** [codeforcauseorg/edu-client#179]
## Is your feature request related to a problem? Please describe.

A referral option in the Profile page under the Activities section. The Referral page shall contain options to refer courses to their friends and also shows the total number of referrals of students at the top.

## Additional context

Courses card can have a small menu button at the rightmost bottom which can contain an option as "Refer to a friend".

**Comment by sakshi-choudhary** [comment]
I would like to work on this if approved @Abhishek-kumar09

**Comment by Abhishek-kumar09** [comment]
I guess you are asking for share button on the coursepage right?

**Comment by Abhishek-kumar09** [comment]
Great idea :)
