### ISSUE TITLE
Adding a notification calendar/Progress bar for the user.

### ISSUE THREAD

**Issue by kritarthmehra** [codeforcauseorg/edu-client#189]
The user can get notifications of upcoming national level exams, competitions/Hackathons etc. Links to the competitions will be provided on a single click and the related courses can also be shown there.

**Comment by badboyguss** [comment]
Can I start working on this?  @Abhishek-kumar09

**Comment by Abhishek-kumar09** [comment]
Great, fetching hackathons and programs is a part of backend, here yoou can create frontend and share design.

**Comment by Abhijay007** [comment]
Is someone still working on this? I would like to work on this @Abhishek-kumar09 @vasudev19126

**Comment by kritarthmehra** [comment]
Yes @Abhijay007 I'll be submitting a PR soon.

**Comment by Abhijay007** [comment]
Ok

**Comment by Abhijay007** [comment]
@kritarthmehra are you still working on it?  if not, can I open a PR for this?

**Comment by kritarthmehra** [comment]
@Abhijay007 Go for it.
