### ISSUE TITLE
A minor correction in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Jassi10000** [codeforcauseorg/edu-client#191]
## Is your feature request related to a problem? Please describe.

In the CONTRIBUTING.md file , under the section of  "Setting up project using yarn"
I think there's a lil mistake in the documentation

## Describe the solution you'd like

1. It should be   " Running in Development Mode  "   instead  of  " Running in Deployment mode  " 
2. There should be instructions to install dependencies with yarn as it can confuze beginners who are just starting with project 
So ,  I want to add there  " yarn install " guideline   likewise its given in   case of  "npm"

## Additional context

Add any other context about the feature request here.
![educlient1](https://user-images.githubusercontent.com/64856348/113442915-91b5dd00-940e-11eb-86a0-71d71c9e8d82.PNG)

This is the screenshot of the portion in which am  requesting to add changes

**Comment by rajatgupta24** [comment]
Hi @Jassi10000, go ahead with this and create a PR.

**Comment by Jassi10000** [comment]
Sure sir , updating that in a few minutes
