### ISSUE TITLE
Create course Details Page

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/edu-client#2]
Full Page pdf: 
[Course Details.pdf](https://github.com/codeforcauseorg/edu-client/files/6114374/Course.Details.pdf)

We are breaking this issues into several sub issues, you are required to solve subissues.
We are MAterial-ui and Ionic-React

**Comment by Ruchip16** [comment]
@Abhishek-kumar09 Can I work on this issue ?

**Comment by ritvij14** [comment]
@Abhishek-kumar09 hello! I came across this project from discord and would like to work on it. Can I work on this issue?

**Comment by SankhaChak** [comment]
Hey @Abhishek-kumar09 , I would love to work on this issue.

**Comment by Abhishek-kumar09** [comment]
This is not the main issue to work on, It is distributed in several child issues they need to be solved to solve this parent issue.

**Comment by raniyer** [comment]
@Abhishek-kumar09  since all the issues are taken, please do consider me for future issues. 🖌️

**Comment by harshshaw** [comment]
Can i work on learn something new and top pick cards ?@Abhishek-kumar09

**Comment by Abhishek-kumar09** [comment]
> Can i work on learn something new and top pick cards ?@Abhishek-kumar09

It is adressed in https://github.com/codeforcauseorg/edu-client/issues/5
