### ISSUE TITLE
Feature Request=> Create Mentor rating and review page.

### ISSUE THREAD

**Issue by sakshi-choudhary** [codeforcauseorg/edu-client#206]
Create Mentor rating and review page.

**Comment by sakshi-choudhary** [comment]
Can I work on this issue? @Abhishek-kumar09

**Comment by Abhishek-kumar09** [comment]
Do you have some design in your mind?

**Comment by sakshi-choudhary** [comment]
Yes, actually it's there in Figma file. I'll make the same like this and maybe enhance a bit.
![](https://cdn.discordapp.com/attachments/748744928514932816/828513810221367326/Screenshot_2021-04-05_at_11.42.22.png)
