### ISSUE TITLE
Add placeholder login page and limit user from seeing content without login

### ISSUE THREAD

**Issue by KeenWarrior** [codeforcauseorg/edu-client#21]
![image](https://user-images.githubusercontent.com/25343183/110754214-8e935b00-826d-11eb-92ef-a4c086269545.png)

**Comment by avinash14022002** [comment]
Can i work?

**Comment by avinash14022002** [comment]
Is the application in java or kotlin?

**Comment by atharmohammad** [comment]
@KeenWarrior  I would like to work on this issue

**Comment by atharmohammad** [comment]
> Is the application in java or kotlin?

It is in react

**Comment by KeenWarrior** [comment]
You can take the login from https://github.com/codeforcauseorg/edu-client/tree/master/src/layouts/MainLayout/TopBar

**Comment by harshshaw** [comment]
@KeenWarrior Can i work ...or please can u assign any upcoming issue to me , my Event issue was closed ... i would love to contribute if assigned any

**Comment by atharmohammad** [comment]
@KeenWarrior  When authenticating via google it returns user object but I can't find access token ,Can you tell me what should I store in local storage to get logged in

![ggg](https://user-images.githubusercontent.com/56029409/110768943-aecb1600-827d-11eb-9943-28ba3fe16773.PNG)
![ggg2](https://user-images.githubusercontent.com/56029409/110768992-bbe80500-827d-11eb-979f-64baf73b0223.PNG)

**Comment by VenomFate-619** [comment]
@atharmohammad token is stored as tokenId  
You refer this
`const googleSuccess = async (res) => { 
    const result =  res?.profileObj
    const token = res?.tokenId  
    try {
        dispatch({ type:"AUTH" , payload:{ result , token } })
        history.push('/')
    } catch (error) {
      console.log(error);
    }
  }`

**Comment by atharmohammad** [comment]
@VenomFate-619  Can you tell me which file it is in
