### ISSUE TITLE
Fix- Overexposed shadow blur radius of cards

### ISSUE THREAD

**Issue by adarsh-technocrat** [codeforcauseorg/edu-client#225]
**Description**
The over-exposed shadow blur radius can be removed to make cards look cleaner and this needs to fix with all cards.

![shadow](https://user-images.githubusercontent.com/47661086/113659853-93a6c700-96c0-11eb-813e-37538d414a8e.PNG)

Cc/ @Abhishek-kumar09

**Comment by naveen8801** [comment]
Hi @adarsh-technocrat  @abhishekkumar08  , I'd like to work on it , can you assign it to me ?

**Comment by adarsh-technocrat** [comment]
Sure @naveen8801  as there is no major change just you need to add css to card with `boxShadow: "0px 0px 5px rgba(0,0,0,0.2)",` 

Hey, @Abhishek-kumar09  you can please assign this issue to @naveen8801 :)

**Comment by naveen8801** [comment]
> Sure @naveen8801 as there is no major change just you need to add css to card with `boxShadow: "0px 0px 5px rgba(0,0,0,0.2)",`
> 
> Hey, @Abhishek-kumar09 you can please assign this issue to @naveen8801 :)

thanks @adarsh-technocrat 👍

**Comment by naveen8801** [comment]
@Abhishek-kumar09 , i have made a [236](https://github.com/codeforcauseorg/edu-client/pull/236) , please review :)

**Comment by Abhijay007** [comment]
@adarsh-technocrat you can close this issue now as it is resolved :)

**Comment by adarsh-technocrat** [comment]
Sure @Abhijay007 !!
