### ISSUE TITLE
Documentation: Provide instructions for android development in CONTRIBUTING.md

### ISSUE THREAD

**Issue by rizwan2000rm** [codeforcauseorg/edu-client#231]
### Update Documentation
The CONTRIBUTING.md is missing instructions for the building and running of android application with capacitor and android studio.

**Comment by karankv26** [comment]
@rizwan2000rm @Abhishek-kumar09 I'll take care of this !

**Comment by rizwan2000rm** [comment]
@karankv26 Sure go ahead.
