### ISSUE TITLE
Job Opening page

### ISSUE THREAD

**Issue by rajatgupta24** [codeforcauseorg/edu-client#240]
## Describe the bug
Hi, I think the job opening page is placed in the wrong place and we should create a different link like **Career** or **Get Involved**.

## To Reproduce

![image](https://user-images.githubusercontent.com/55191777/114074617-311d1900-98c2-11eb-9c41-db03df41d2b1.png)

## Expected behavior
There should be a link on the profile page for jobs

- OS: Firefox
- Browser: Linux (ubuntu)

**Comment by rajatgupta24** [comment]
@Abhishek-kumar09, If you like the suggestion I'd like to get assigned.

**Comment by vasudev19126** [comment]
@rajatgupta24 Yeah go ahead. I also thought that it was placed wrong.

**Comment by adarsh-technocrat** [comment]
Hey, @rajatgupta24  are you working on this issue!

**Comment by rajatgupta24** [comment]
> Hey, @rajatgupta24 are you working on this issue!

Yup, I've added this change in my PR it's currently in progress, due to some other issues.

**Comment by adarsh-technocrat** [comment]
> > Hey, @rajatgupta24 are you working on this issue!
> 
> Yup, I've added this change in my PR it's currently in progress, due to some other issues.

ooh, great  @rajatgupta24  :)

**Comment by rajatgupta24** [comment]
Hey @adarsh-technocrat & @vasudevsinghal, I've added the link in the footer of the profile page, you can see it out in recent pull, so I'm closing this issue 😄
