### ISSUE TITLE
Fix: Breaking UI in Cards

### ISSUE THREAD

**Issue by sakshi-choudhary** [codeforcauseorg/edu-client#241]
## Describe the bug

Overlapping cards in the classroom page

## To Reproduce

1. Go to profile options
2. Open classroom

## Expected behavior
There should some spacing in x-axis between the cards

## Environment (please complete the following information):

- OS: MacOS
- Browser: Chrome

## Additional context

**PREVIEW**
<img src="https://cdn.discordapp.com/attachments/748744928514932816/829953591833395210/image0.jpg" width="300">

**Comment by sakshi-choudhary** [comment]
@Abhishek-kumar09  I would like to fix this issue. Please assign this to me

**Comment by adarsh-technocrat** [comment]
> @Abhishek-kumar09 I would like to fix this issue. Please assign this to me

Hey @sakshi-choudhary than you can make changes here as well 
![WhatsApp Image 2021-04-09 at 5 05 56 PM](https://user-images.githubusercontent.com/47661086/114174296-0ed4db00-9956-11eb-8517-cbc2ef92c829.jpeg)

**Comment by sakshi-choudhary** [comment]
> > @Abhishek-kumar09 I would like to fix this issue. Please assign this to me
> 
> Hey @sakshi-choudhary than you can make changes here as well
> <img alt="" width="200" src="https://user-images.githubusercontent.com/47661086/114174296-0ed4db00-9956-11eb-8517-cbc2ef92c829.jpeg">

Sure, will do
