### ISSUE TITLE
Idea of Backend Migration to LoopBack or Next or Meteor 

### ISSUE THREAD

**Issue by Jassi10000** [codeforcauseorg/edu-client#250]
## Is your feature request related to a problem? Please describe.

After thinking about the applciation in all aspects , one thing that came in my mind is the Edu-Client will one day be treated as a Production Level Application and thus I came up with this solution

## Describe the solution you'd like

Presently , we are using traces of Express.Js with Node.Js at the backend of the application , but to made it more scalable , maintainable and flexible the  application  can have the backend in   LoopBack.Js   or   Next.Js    or  Meteor.Js   <-----------  These 3 frameworks give a strong competiition to Express Backend  according to  statistics of  Github Stars in 2021
@kunal-kushwaha  @Abhishek-kumar09  @KeenWarrior  Please give you views regarding this

## Additional context

Add any other context about the feature request here.

**Comment by Abhishek-kumar09** [comment]
We are using nestJS as our backend.
That is edu-server app.

I am closing this issue for rest of issue management. If you have some confusions feel free to reopen it anytime.
