### ISSUE TITLE
Add Highlight feature for the selected video on the 'Individual Courses Page'

### ISSUE THREAD

**Issue by samad-yar-khan** [codeforcauseorg/edu-client#252]
## Is your feature request related to a problem? Please describe.

In the Individual Courses page there is no indication regarding the video which is currently selected . Even after clicking on the component there is no change .

![before1](https://user-images.githubusercontent.com/70485812/114304844-04037d00-9af3-11eb-8e58-e85b774e7142.PNG)

## Describe the solution you'd like

I would like to add a method which detects the currently selected video and highlights the ListItem as shown below .
![after1](https://user-images.githubusercontent.com/70485812/114304897-44fb9180-9af3-11eb-8085-fcfb1badedf2.PNG)

**Comment by samad-yar-khan** [comment]
@Abhishek-kumar09 I would like to work on this issue. Can you please assign this to me .

**Comment by samad-yar-khan** [comment]
@Abhishek-kumar09  Just tagging again in case the comment has been missed . In case the issue is not significant or you guys are going for a different design aesthetic you can let me know :)

**Comment by Abhishek-kumar09** [comment]
Sorry for the delay @samad-yar-khan 
You can proceed with the feature, You already have the figma, please let me know if you need anything else.
