### ISSUE TITLE
Add functionality to delete items from the wishlist section

### ISSUE THREAD

**Issue by Abhijay007** [codeforcauseorg/edu-client#256]
## Is your feature request related to a problem? Please describe.

Add a user functionality to delete items/courses from the "Wishlist" section on click of that delete button.

## Additional context

![wishlist-section](https://user-images.githubusercontent.com/64387054/114316001-3a56f180-9b1f-11eb-8431-0d442a72c87d.gif)

**Comment by adarsh-technocrat** [comment]
Hey, @Abhijay007  are you working on this issue? if not then I can go for making PR for this issue :)

**Comment by Abhijay007** [comment]
> Hey, @Abhijay007 are you working on this issue? if not then I can go for making PR for this issue :)

yes, @adarsh-technocrat I am working on it but No problem you can open a PR for this, As maybe we are both using different approaches. We will let mentors decide which code is more efficient.  they will merge code accordingly after review. 

And one more thing I want to mention that when you write code for the DELETE wishlist component try to write code or ADD functionality as well :)

**Comment by adarsh-technocrat** [comment]
oooh Great! no problem @Abhijay007 if you are stuck anywhere we can discuss the solution in this thread same goes for me 😊!

**Comment by Abhijay007** [comment]
> oooh Great! no problem @Abhijay007 if you are stuck anywhere we can discuss the solution in this thread same goes for me 😊!

ya ok 😊!!
