### ISSUE TITLE
Redesign UI  of the contest page

### ISSUE THREAD

**Issue by adarsh-technocrat** [codeforcauseorg/edu-client#259]
## Is your feature request related to a problem? Please describe.

**Proposed UI of the contest page** 

<p align ="middle">
<img src="https://user-images.githubusercontent.com/47661086/114812862-811e4300-9dce-11eb-8a4d-c621b1e42997.png" hight="400" width="200"/>
<img src="https://user-images.githubusercontent.com/47661086/114811577-f4728580-9dcb-11eb-8d28-51ef258212b9.png" hight="400" width="200"/>
<img src="https://user-images.githubusercontent.com/47661086/114812803-6350de00-9dce-11eb-93c5-dc1f80d7476d.png" hight="400" width="200"/>
</p>

As the previous Design of Contest page  was similar to the Assignment Section  I think this Proposed change can go well with the  contest page 

## Additional context

Add any other context about the feature request here.
 Cc/ @Abhishek-kumar09 , @KeenWarrior  , @kunal-kushwaha

**Comment by adarsh-technocrat** [comment]
Hey, @Abhishek-kumar09  can you please assign this to me :)

**Comment by sakshi-choudhary** [comment]
@adarsh-technocrat  I don't think this design will be a good UX, people are more likely to scroll vertically than horizontally. In the current one, there's contests mentioned in list way, and its an accordion, you can put the leaderboard part and link it to the know more button which is there currently, also you can put timer part if you want. And no need for stats, stats PR #237 has been made already there is a page for stats linked through the contest page. Its my point of view, Rest @Abhishek-kumar09 can tell.

**Comment by adarsh-technocrat** [comment]
> And no need for stats, stats PR #237 has been made already there is a page for stats linked through the contest page. It's my point of view, Rest @Abhishek-kumar09 can tell.

Hey, @sakshi-choudhary  your point is right people are more likely to scroll vertically than horizontally but the idea is we are not showing the complete contests list on one screen but we are giving options to users to choose the contests according to their interest as I have given separate buttons for separate categories of contests and accordingly we can show a vertical list of ongoing and upcoming contests by clicking on that buttons.

And on the top horizontally scroll list it will only show the live contests but if the user clicks on the `view all` text button the user will navigate to the `live contests screen `and able to see all live contests in `vertical view`  and also able to perform the filter operations according to tags like "CFC Hack".

And about the stats part, I have given the `previous stats` button on `your stats card ` in the given design which will navigate to the statistic page that you have created. if I'm not wrong the stats page you have created is more focused on graphs and charts so I thought of adding a stats card so that user has a clear view of their participation like mentioned in the given design.

I think this might make you clear with the design if not I would love to have your thoughts and suggestions to make this design better in terms of UI and UX :)

**Comment by adarsh-technocrat** [comment]
Any reverts on this proposed change @Abhishek-kumar09, @sakshi-choudhary?
waiting for approval :)
