### ISSUE TITLE
Link to Rate Mentor Page

### ISSUE THREAD

**Issue by sakshi-choudhary** [codeforcauseorg/edu-client#261]
## Is your feature request related to a problem? Please describe.

Currently, there is no option that links to rate the mentor page (the page is already created).

## Describe the solution you'd like

I want to add one more option here called as - Rate the mentor and link it to the rate mentor page.

<img src="https://user-images.githubusercontent.com/66865329/114492758-d58eba80-9c36-11eb-8086-a9467bcc0734.jpg" width="250">

**Comment by sakshi-choudhary** [comment]
@Abhishek-kumar09  Please assign this to me.

**Comment by vasudev19126** [comment]
@sakshi-choudhary  Yeah go ahead
