### ISSUE TITLE
Create design for About Us page

### ISSUE THREAD

**Issue by poojadas07** [codeforcauseorg/edu-client#266]
## Is your feature request related to a problem? Please describe.

About us page contains different sections like Who we are , Our Vision & Mission , Our team members and small content about all these sections. 

## Describe the solution you'd like

A new page (aboutus) located under the profile section .

**Comment by poojadas07** [comment]
@Abhishek-kumar09 Can I work on this?

**Comment by vasudev19126** [comment]
@poojadas07 Yeah go ahead.

**Comment by sakshi-choudhary** [comment]
@vasudev19126 @poojadas07  I think an about us page already exist with our mission, team, etc.

**Comment by vasudev19126** [comment]
@poojadas07  you are replacing it to under the profile section, right?

**Comment by poojadas07** [comment]
> @vasudev19126 @poojadas07 I think an about us page already exist with our mission, team, etc.
Yeahh...I want to change the UI of About Page.

**Comment by vasudev19126** [comment]
@poojadas07 So what UI are you suggesting?
