### ISSUE TITLE
About Us page is Added in the React-Swipeable Routes

### ISSUE THREAD

**Issue by ADRE9** [codeforcauseorg/edu-client#269]
## Describe the bug
The about us page has been added to the react-swipeable routes so when the user swipes right from the home page he/she gets stuck at the about us page.

## To Reproduce

1.Make the Route of About Us page outside the scope of react-swipeable routes.
2. Add a comment in the project to warn developers not to add any route in the scope of react-swipeable routes.

## Expected behavior
About Us page wont be available when swiped right from the home screen.

## Environment:

- OS: Windows
- Browser: Edge

**Comment by ADRE9** [comment]
@KeenWarrior can I solve this minor issue?

**Comment by Abhishek-kumar09** [comment]
Sure
