### ISSUE TITLE
Bottom Navigation Button 

### ISSUE THREAD

**Issue by rajatgupta24** [codeforcauseorg/edu-client#27]
Hi @Siddhant-K-code ,
Text of button doesn't change with the size, we should use css instead of material-ui (so that we can use "rem")
![image](https://user-images.githubusercontent.com/55191777/110772608-cc9a7a00-8281-11eb-80cb-c234aaab0818.png)

**Comment by KeenWarrior** [comment]
@rajatgupta24 Material-UI is an indispensable tool for us. You all always use CSS with mui. Take a look around the internet to learn how.

**Comment by rajatgupta24** [comment]
Ok @KeenWarrior  then I'll use CSS to change mui styles

**Comment by Abhishek-kumar09** [comment]
closed in #78

**Comment by rajatgupta24** [comment]
I think it isn't fixed yet.
![image](https://user-images.githubusercontent.com/55191777/111586666-2dc4cf00-87e7-11eb-9530-7be746d18e59.png)
