### ISSUE TITLE
The back button is not required.

### ISSUE THREAD

**Issue by ADRE9** [codeforcauseorg/edu-client#270]
## Describe the bug
The back button is not required and if also it is kept it should not work as a back button of browser that on getting clicked changes the page to the last visited page, since the UI of app dies using the back button and it looks for of a webapp.

## To Reproduce

1.To remove back button from the header
2.Or if not to attach the route of left page so that on clicking back user goes to the previous page.

## Environment (please complete the following information):

- OS: Windows 
- Browser: Firefox

**Comment by ADRE9** [comment]
@Abhishek-kumar09  @KeenWarrior do you think the functionality of the back button well defined?

**Comment by rizwan2000rm** [comment]
You are talking about the back button on Course Details Page ?

**Comment by ADRE9** [comment]
The one at the header at every page except the Home page.

**Comment by Abhishek-kumar09** [comment]
As you have thought the back is not needed on the MainLayout pages, since there is bottomNavigation to handle all those things.

But we will be needing back button on independent pages.

Is using `hisstory.goBack()` is making any problem for app UX @ADRE9

**Comment by ADRE9** [comment]
Yes , that's okay for other pages but for the main pages that can b navigated through the bottom navigation the default behaviour must be to visit the left page instead of going back in history, I guess that's the default behaviour for the mobile applications.

**Comment by Abhishek-kumar09** [comment]
Totally Agree.

**Comment by Abhishek-kumar09** [comment]
Do you want to work on it?

**Comment by ADRE9** [comment]
Yes please , but should I remove it or should I just re-route to the previous pages?

**Comment by Abhishek-kumar09** [comment]
remove it.
