### ISSUE TITLE
Repeated Code

### ISSUE THREAD

**Issue by rajatgupta24** [codeforcauseorg/edu-client#276]
## Is your feature request related to a problem? Please describe.

Hey @Abhishek-kumar09, I noticed that we are writing the **top navigation** in each section page which is not preferable & using **Back Arrow** on pages like **wishlist**, **myCourses**, or **profile** doesn't make sense.

## Describe the solution you'd like

I think it's better to create a **component** for **top navigation** for the page where we're not having **bottomNav**

## Additional context

Add any other context about the feature request here.

**Comment by rizwan2000rm** [comment]
@rajatgupta24 I think the back button problem is mentioned in issue #270

**Comment by rajatgupta24** [comment]
> @rajatgupta24 I think the back button problem is mentioned in issue #270

Sorry didn't notice it before

**Comment by Abhijay007** [comment]
@rajatgupta24  you can close this issue now :)
