### ISSUE TITLE
Convert Scroll To Top button as a FAB

### ISSUE THREAD

**Issue by dhwaj1902** [codeforcauseorg/edu-client#277]
Currently, the scroll to top button is at the bottom of the page, and we have to add ScrollToTop Component on every page separately. 
Like this:
![image](https://user-images.githubusercontent.com/57860123/115421053-462a6e00-a219-11eb-8aac-906974826eb4.png)

There can be a FAB(Floating Action Button) at the right bottom side of the screen, which is activated whenever the screen scroll is greater than some value, say 400.
Like this: 
```
if (window.pageYOffset > 400) {
      ...
}
```
And I can implement it in such a way that we do not need to separately include on each and every page.

**Comment by rizwan2000rm** [comment]
Yes I think floating button would be nice.

Just make sure it doesn't appear until you actually scroll down.

**Comment by Abhijay007** [comment]
@dhwaj1902  you can close this issue now :)
