### ISSUE TITLE
Adding referral section in  profile page

### ISSUE THREAD

**Issue by adarsh-technocrat** [codeforcauseorg/edu-client#279]
**Description**

The idea is to add a referral section on the Profile Page which will allow the user to share referrals and avale some kind of offer.
I think this could be a valid change because most of the education platform has this feature. 

Here is a possible UI of the screen it could be changed accordingly as per the requirement.

<img src="https://user-images.githubusercontent.com/47661086/115841732-ba902780-a43a-11eb-9c48-7f00f0dec713.png" hight="400" width="200"/>

Cc/ @Abhishek-kumar09 what are your thoughts on this?

**Comment by vasudev19126** [comment]
@adarsh-technocrat  yeah, go ahead
