### ISSUE TITLE
Typo error 

### ISSUE THREAD

**Issue by rajatgupta24** [codeforcauseorg/edu-client#28]
Hi @Siddhant-K-code, 
BottomNav.js file in "client/src/layouts/MainLayout/" is BoottomNav.js
I think i should change it.

**Comment by KeenWarrior** [comment]
Sure. Go ahead

**Comment by aflah02** [comment]
Hey @KeenWarrior I fixed this issue and was just going to file a pull request when I saw this what should I do now?

**Comment by KeenWarrior** [comment]
@aflah02 Whenever you find an issue. Before filing PR. 

First, create an issue and get it assigned to yourself.

In case of a minor issue like this ( changes less than few lines ), you can self-assign as well. But creating an issue is important before starting.

**Comment by aflah02** [comment]
Ohkk I'll keep that in mind i'll leave this to @rajatgupta24 then.
Thanks @KeenWarrior
