### ISSUE TITLE
Design for Edit Profile in Profile Page

### ISSUE THREAD

**Issue by poojadas07** [codeforcauseorg/edu-client#282]
## Is your feature request related to a problem? Please describe.

Profile edit popup contain a form so that we can change the name , logo and email .

## Describe the solution you'd like
![edit](https://user-images.githubusercontent.com/66192403/115905090-3c0ba800-a483-11eb-90da-f9452398d427.PNG)

**Comment by poojadas07** [comment]
@Abhishek-kumar09 Please check and let me know !

**Comment by poojadas07** [comment]
> ## Is your feature request related to a problem? Please describe.
> Profile edit popup contain a form so that we can change the name , logo and email .
> 
> ## Describe the solution you'd like
![edit](https://user-images.githubusercontent.com/66192403/115905029-28f8d800-a483-11eb-8de1-ddd38a4b9891.PNG)

**Comment by Abhishek-kumar09** [comment]
Instead of popup we can try to make a new page for that.

**Comment by poojadas07** [comment]
> Instead of popup we can try to make a new page for that.

Cool
