### ISSUE TITLE
Fix Discussion Forum

### ISSUE THREAD

**Issue by sakshi-choudhary** [codeforcauseorg/edu-client#285]
## Describe the bug

The UI/UX of the current discussion forum is quite bad.
I will fix and update the current UI and show posts and comments in a better manner.
- I’ll add file uploading option as well
- All Comments will open in a new page 
- Search discussion by topic UI
- Filter discussion option

**Comment by sakshi-choudhary** [comment]
Please assign this to me @Abhishek-kumar09

**Comment by Abhijay007** [comment]
@sakshi-choudhary this issue is resolved by your PR (#290), you can close it now :).
