### ISSUE TITLE
Addition of Wishlist Icon for every course

### ISSUE THREAD

**Issue by poojadas07** [codeforcauseorg/edu-client#297]
## Is your feature request related to a problem? Please describe.

I want to add one wishlist icon on every course description and save note icon should be there in the header.

## Describe the solution you'd like

https://user-images.githubusercontent.com/66192403/116366330-cf4a3200-a823-11eb-84a3-b9987b8e0c4c.mp4

**Comment by poojadas07** [comment]
@Abhishek-kumar09 Have a look and tell me.

**Comment by sakshi-choudhary** [comment]
@poojadas07 I don't think add note option should be on the header, that's not a good UX. It should be as a floating action button only at bottom right, the way as it is right now.

**Comment by Abhishek-kumar09** [comment]
Adding a heart icon looks good to me.

**Comment by poojadas07** [comment]
> @poojadas07 I don't think add note option should be on the header, that's not a good UX. It should be as a floating action button only at bottom right, the way as it is right now.

okay...
