### ISSUE TITLE
Develop About Course Page

### ISSUE THREAD

**Issue by sakshi-choudhary** [codeforcauseorg/edu-client#298]
## Describe the solution you'd like

Develop an about course page.

## Additional context

The page will be linked to this option present currently in each course's more options.
<img width="300" src="https://user-images.githubusercontent.com/66865329/116412870-b60da980-a854-11eb-9b80-a8c247ede236.jpeg">

**Comment by sakshi-choudhary** [comment]
@Abhishek-kumar09 @vasudev19126 Can I work on this?

**Comment by vasudev19126** [comment]
@sakshi-choudhary yes

**Comment by Abhishek-kumar09** [comment]
@sakshi-choudhary I think this is already desined, https://edu-client.netlify.app/course/2
Are you thinking something else?

**Comment by sakshi-choudhary** [comment]
> @sakshi-choudhary I think this is already created, https://edu-client.netlify.app/course/2
> Are you thinking something else?

Okay, yeah but this for new users right? as there's an option to buy as well. So, do we need an about course page for enrolled students? as I saw this about course option the more options tab.

**Comment by adarsh-technocrat** [comment]
Hey, @sakshi-choudhary  I don't think it will be a good idea for making a difference about course page route for this section rather what we can do is we can make that list to expanded and collapse list and show a summary of about course. This will also help users to see course details while attending the lectures.

Please let me know your thoughts on this :)

**Comment by sakshi-choudhary** [comment]
> Hey, @sakshi-choudhary I don't think it will be a good idea for making a difference about course page route for this section rather what we can do is we can make that list to expanded and collapse list and show a summary of about course. This will also help users to see course details while attending the lectures.
> 
> Please let me know your thoughts on this :)

Yes, a collapse will be fine.

**Comment by Abhijay007** [comment]
@sakshi-choudhary this issue is resolved by your PR (#309), I think you can close it now : )
