### ISSUE TITLE
Create Hero for Course Detail Page

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/edu-client#3]
Part 1 of #2

![image](https://user-images.githubusercontent.com/48255244/110599876-57f40c80-81a9-11eb-9bd9-70b242030abb.png)

Compoenents are required to be made with material-ui: https://material-ui.com/

**Comment by rizwan2000rm** [comment]
Can I work on this issue @Abhishek-kumar09 ?

**Comment by Abhishek-kumar09** [comment]
Yes, go on.

**Comment by rizwan2000rm** [comment]
@KeenWarrior @Abhishek-kumar09 I have started working on this issue. The fonts and colors has not been added to the repo yet. Also can someone ellaborate on trailer section of hero like is it a embeded video or a custom component ?

**Comment by Abhishek-kumar09** [comment]
It's an embedded video, that should play once clicked. It's a good npm package for doing it: https://www.npmjs.com/package/video-react

**Comment by rizwan2000rm** [comment]
@Abhishek-kumar09 Looks like the video-react project is abandoned I found a better alternative called react-player:
https://github.com/cookpete/react-player
I added it works fine as we expect, it lazy loads the player on click also has pip mode.
Also what about fonts and colors is someone going to add colors in Material UI Theme ? I'm just using secondary color for now also added a tag for Roboto font from Google Fonts.

**Comment by Abhishek-kumar09** [comment]
> @Abhishek-kumar09 Looks like the video-react project is abandoned I found a better alternative called react-player:
> [cookpete/react-player](https://github.com/cookpete/react-player)
> I have added it and works fine as we expect, it lazy loads the player on click plus has pip mode.
> Also what about fonts and colors is someone going to add colors in Material UI Theme ? I'm just using secondary color for now also added a tag for Roboto font from Google Fonts.

Okay react-player is also good, we can play youtube videos right inside it. Does it have controls too.
I have added theme.

**Comment by rizwan2000rm** [comment]
@Abhishek-kumar09 Yes it does have all controls like volume, fullscreen and play/pause.
Here is what hero looks like now
![Course Details Responsive Hero](https://user-images.githubusercontent.com/48753482/110764386-01560380-8279-11eb-825b-027194206890.png)

@KeenWarrior 
But after pulling the recent changes I'm having issues with scrolling. Even testing on different page, the issue still persists. I cannot figure out what caused scrolling to stop. Anything beyond the viewport is unreachable. Looks like it is something within common Layout wrapper. Please check it on your side and raise an issue if needed.

**Comment by Abhishek-kumar09** [comment]
Create a PR and I will look to it.
