### ISSUE TITLE
scrollable list in Wishlist page.

### ISSUE THREAD

**Issue by dhwaj1902** [codeforcauseorg/edu-client#30]
The present wishlist page does not scroll.

**Comment by KeenWarrior** [comment]
@dhwaj1902 Please elaborate on this

**Comment by KeenWarrior** [comment]
Is it the same problem with other pages as well? What is your analysis, why is it happening?

**Comment by dhwaj1902** [comment]
I have solved Wishlist page scroll and for the other pages I am checking.

**Comment by Abhishek-kumar09** [comment]
> I have solved Wishlist page scroll and for the other pages I am checking.

Oh @dhwaj1902 Really sorry I saw your comment little late, the fix is merged in https://github.com/codeforcauseorg/edu-client/commit/44c916fa4fe8eeeea6b2eaebe08aa036fc01e1c6
