### ISSUE TITLE
Fix routing of about course section

### ISSUE THREAD

**Issue by adarsh-technocrat** [codeforcauseorg/edu-client#300]
**Description**

As currently, we are routing to the About course section through the checkout button from the wishlist section I think that should not be the right position for routing to the about course page rather we can use the checkout button to route to the checkout section which is not used anywhere right now and by clicking course media card we can route to About course page.

Cc/ @Abhishek-kumar09, @vasudev19126

**Comment by sakshi-choudhary** [comment]
Yes, you are right the page should not be linked to the checkout button, but  by clicking course media card the page should open.

**Comment by sakshi-choudhary** [comment]
<img width="404" alt="Screenshot 2021-04-29 at 14 48 18" src="https://user-images.githubusercontent.com/66865329/116529608-cc6e4080-a8fa-11eb-8166-e52f0162b165.png">
Also, these should be linked to the about course page. Please, do link these as well. @adarsh-technocrat 
cc @Abhishek-kumar09

**Comment by naveen8801** [comment]
Hi @adarsh-technocrat  @Abhishek-kumar09 can i work on this ?

**Comment by adarsh-technocrat** [comment]
Hey @naveen8801  actually there is not major change to the issue and I have resolved this issue in my local system just need to push that I'll close this issue today :)

Thanks, @naveen8801  for your interest 😊

**Comment by adarsh-technocrat** [comment]
Closed via #304
