### ISSUE TITLE
Develop Buy Course Page

### ISSUE THREAD

**Issue by sakshi-choudhary** [codeforcauseorg/edu-client#301]
## Describe the solution you'd like

Develop the buy course page given in the figma design, this will be linked to buy course button and checkout button.

## Design

<img src="https://user-images.githubusercontent.com/66865329/116528968-0d198a00-a8fa-11eb-9c2b-26f0597e5b8e.png" width="400">

**Comment by sakshi-choudhary** [comment]
@Abhishek-kumar09 Please assign this to me

**Comment by adarsh-technocrat** [comment]
Hey, @sakshi-choudhary we already have a checkout page UI ready just the thing is it's not linked to any button you check `Routes.js`   that's what I mentioned in issue #300.
