### ISSUE TITLE
Add exit animation after deleting the Wishlist card

### ISSUE THREAD

**Issue by adarsh-technocrat** [codeforcauseorg/edu-client#308]
## Describe the bug

The issue is after deleting the wishlist card there is no exit animation for visual feedback to the user. So that should be added to see if the wishlist card is deleted or not.

Cc/ @Abhishek-kumar09  , @vasudevsinghal

**Comment by RohankumarM** [comment]
@Abhishek-kumar09 Can you assign this to me?

**Comment by adarsh-technocrat** [comment]
Hey @RohankumarM   you can work on this issue :)

**Comment by adarsh-technocrat** [comment]
issue fix via #332
