### ISSUE TITLE
Recent Searches section in home page

### ISSUE THREAD

**Issue by poojadas07** [codeforcauseorg/edu-client#315]
## Is your feature request related to a problem? Please describe.

Recent searches section in homepage. 
 
## Describe the solution you'd like

I want to add one more section in home page which contains all the recent searches of the particular login user. Recent searches vary from user to user according to userId or userEmail.

**Comment by poojadas07** [comment]
> ## Is your feature request related to a problem? Please describe.
> Recent searches section in homepage.
> 
> ## Describe the solution you'd like
> I want to add one more section in home page which contains all the recent searches of the particular login user. Recent searches vary from user to user according to userId or userEmail.

@Abhishek-kumar09 I want to work on this. Please assign to me.

**Comment by Abhishek-kumar09** [comment]
This is a good feature to implement, but we can halt this for sometime.Just asking If you would like to work on the shadow portion of courses which are looking wierd (See the shadow of bottom of card).

**Comment by poojadas07** [comment]
> This is a good feature to implement, but we can halt this for sometime.Just asking If you would like to work on the shadow portion of courses which are looking wierd (See the shadow of bottom of card on homepage).

Okay....
Sure , I will work on the shadow of course card.

**Comment by adarsh-technocrat** [comment]
> > This is a good feature to implement, but we can halt this for sometime.Just asking If you would like to work on the shadow portion of courses which are looking wierd (See the shadow of bottom of card on homepage).
> 
> Okay....
> Sure , I will work on the shadow of course card.

Actually @poojadas07  @Abhishek-kumar09  there is already open PR for that #236 is this is not the right change?

**Comment by poojadas07** [comment]
![home](https://user-images.githubusercontent.com/66192403/117934031-d5f6a000-b31f-11eb-8ca8-eaf2a0285190.PNG)
![courses](https://user-images.githubusercontent.com/66192403/117934042-d8f19080-b31f-11eb-8f16-d35dd60c8a73.PNG)
![wish](https://user-images.githubusercontent.com/66192403/117934047-db53ea80-b31f-11eb-8d24-0cb5eeb09c7b.PNG)

@Abhishek-kumar09 Please check !!
