### ISSUE TITLE
Develop Navbar for Web app

### ISSUE THREAD

**Issue by sakshi-choudhary** [codeforcauseorg/edu-client#324]
## Is your feature request related to a problem? Please describe.

I'll develop a navbar component for the web app view. Whenever someone is making any page responsive they can use this navbar on that particular page for web app view.

## Describe the solution you'd like

This is a proposed design.

<img width="989" alt="Screenshot 2021-05-11 at 18 33 21" src="https://user-images.githubusercontent.com/66865329/117828962-efe8a200-b28f-11eb-86ba-493d71a12fb6.png">

on clicking the user icon this `drawer` will open.

<img width="989" alt="Screenshot 2021-05-11 at 18 33 21" src="https://user-images.githubusercontent.com/66865329/117821222-fc1d3100-b288-11eb-9599-174686e91da9.png">

**Comment by santu-2024** [comment]
Would it cover the full desktop space on a web page?
