### ISSUE TITLE
Header and Navbar for the application

### ISSUE THREAD

**Issue by aks1809** [codeforcauseorg/edu-client#33]
A header along with a navbar which are responsive and provide a user name and login and logout buttons.

**Comment by Striver08** [comment]
I would like to work on this

**Comment by aks1809** [comment]
Actually I was thinking of working on this and was waiting for approval.

**Comment by KeenWarrior** [comment]
@Abhishek-kumar09 We will discuss the design in the coming meeting. But I feel the header would not good way with the current design.

**Comment by KeenWarrior** [comment]
Login will be the first action and logout from a course app is not frequent and need not be on the very top.

**Comment by aks1809** [comment]
Is there a way I could get some design that is intended for the website or perhaps could communicate with you guys to develop figma designs?

**Comment by Abhishek-kumar09** [comment]
Login is managed in a seperate page.

Closing this issue to get hold of newer issues.

Please open it anytime if required.
