### ISSUE TITLE
Adding a custom Scroll bar 

### ISSUE THREAD

**Issue by harkiratsm** [codeforcauseorg/edu-client#349]
Adding a custom scroll bar on the page would make website more interactive.

**Comment by niteshseram** [comment]
Hello, is this issue needed to be fixed? If yes, can I work on this?

**Comment by adarsh-technocrat** [comment]
Hey, @niteshseram  do you want to work on this issue!

**Comment by niteshseram** [comment]
@adarsh-technocrat yes

**Comment by adarsh-technocrat** [comment]
> @adarsh-technocrat yes

Go ahead @niteshseram :)

**Comment by adarsh-technocrat** [comment]
Any reasons for closing this issue @harkiratsm?
