### ISSUE TITLE
Text overlapping and UI inconsistency in the mobile view of "our impact "section of home page 

### ISSUE THREAD

**Issue by Abhijay007** [codeforcauseorg/edu-client#356]
## Describe the bug

A text overlapping between the text and card in the "our impact" section exists in the desktop view of the application.

![desktop overlapping](https://user-images.githubusercontent.com/64387054/121068505-fd8b3c00-c7e9-11eb-8c3f-639344882217.PNG)

Also in mobile view, stats card placing looks a bit inconsistent, I think placing the cards horizontally instead of side by side could be a better approach in mobile view.

![mobile_view](https://user-images.githubusercontent.com/64387054/121068983-9326cb80-c7ea-11eb-911a-58cdaf17fc3e.PNG)

## To Reproduce

1. Run the app on localhost 3000 and 
2. Bug exists between ratio( 1375 x 647 as per my machine screen ratio )
3. For mobile view use chrome inspect 

## Expected behavior

text and cards to be displayed side by side without overlapping each other and with a minor gap in bewtten

## Environment (please complete the following information):

- OS: windows
- Browser: chrome

**Comment by adarsh-technocrat** [comment]
Hey, @Abhijay007 I think we have resolved this issue  !!

**Comment by Abhijay007** [comment]
closed #356 via #361
