### ISSUE TITLE
Delay in removing the loginScreen if the user is already signed In

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/edu-client#365]
## Describe the bug

Even if the user is signed in, the user is directed to Login page and remain there for some seconds that get directed elsewhere
# Expected Behaviour
Almost No waiting time

## Environment (please complete the following information):

- OS: Ubuntu 20.04
- Browser: Firefox

**Comment by adarsh-technocrat** [comment]
issue fixed via #364
