### ISSUE TITLE
Can't scroll the wishlist section

### ISSUE THREAD

**Issue by rajatgupta24** [codeforcauseorg/edu-client#37]
## Describe the bug
The Wishlist section card at the end is overlaped by the bottom navbar
![image](https://user-images.githubusercontent.com/55191777/110797501-26f60380-829f-11eb-8090-81dcba85f9c6.png)

## To Reproduce
1. Try to scroll the wishlist section.

## Environment (please complete the following information):
 - OS: ubuntu
 - Browser: firefox

## Additional context
So I think we should add a little padding at the end.

**Comment by rizwan2000rm** [comment]
Yes in layout there is just a paddingTop for navbar. Adding vertical padding something like "64px 0" fixes this issue.

**Comment by rajatgupta24** [comment]
@KeenWarrior Should I make a PR

**Comment by rajatgupta24** [comment]
@Abhishek-kumar09 @KeenWarrior can you please review the #60

**Comment by Abhishek-kumar09** [comment]
Fixed in https://github.com/codeforcauseorg/edu-client/pull/60
