### ISSUE TITLE
Cropped text in Gamification Board page

### ISSUE THREAD

**Issue by abhishek2x** [codeforcauseorg/edu-client#389]
## To Reproduce

Steps to reproduce the behaviour:

1. open Gamification page of the application

## Expected behavior

The text should not be cropped

## Logs

If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):

- OS: Linux
- Browser: Microsoft Edge

## Additional context

![image](https://user-images.githubusercontent.com/53976003/127752485-b0da0de2-f294-421f-9754-366593829f36.png)

**Comment by abhishek2x** [comment]
I want to work on this issue

**Comment by abhishek2x** [comment]
@adarsh-technocrat can you please look into this?

**Comment by adarsh-technocrat** [comment]
> @adarsh-technocrat can you please look into this?

Hi, @abhishek2x   can you please provide for which screen size you made this change! and it would be better if you could provide the output of the change that you made :)

**Comment by abhishek2x** [comment]
Sure, here are the required screenshots for different screen sizes.

**Breakpoint: 755px**

#### For width >= 755px

![image](https://user-images.githubusercontent.com/53976003/130049150-66415ec0-a73b-4ac7-b6b6-f7522ab140fa.png)

#### For width < 755px

![image](https://user-images.githubusercontent.com/53976003/130049264-7aae2e5d-073d-473a-a721-9f2c0ce04555.png)

**Comment by adarsh-technocrat** [comment]
Hey, @abhishek2x  the change looks great but the thing is you have hardcoded the screen width right and that is what @Abhishek-kumar09  has mentioned in the PR  we can find either different way to solve this issue and those breakpoints are filled with some custom values either you can play with those values   **theme/index.js**

**Comment by abhishek2x** [comment]
Alright, I'll figure out a way around and update the PR.
Thanks!
