### ISSUE TITLE
Create swipeable views to swipe to change between the pages.

### ISSUE THREAD

**Issue by ADRE9** [codeforcauseorg/edu-client#39]
## Adding Swipeable Views
Since the app is focused for mobile we can use in-built feature of material-ui to make the views swipeable . Swipeable in the sense that the user can navigate through the pages swiping left or right. 

## React-swipeable-views 
To be able to make the views swipeable .We need to drop React Routing from the views. If the team is not planning on lazy loading the pages or code splitting, this feature is a must since it will give the user a mobile like experience.A major refractor needs to be done to support swipeable views.
Refer:-https://material-ui.com/components/tabs/  
![abc](https://user-images.githubusercontent.com/49809895/110811025-57906a00-82ac-11eb-80a1-9e0b0841512f.jpg)

**Comment by ADRE9** [comment]
## The code structure some what looks like this.
![Screenshot 2021-03-11 205947](https://user-images.githubusercontent.com/49809895/110811488-bf46b500-82ac-11eb-9466-b2f14d5b37fe.jpg)

**Comment by ADRE9** [comment]
Routing is not possible with this approach. @Abhishek-kumar09 . Can you look into it?

**Comment by KeenWarrior** [comment]
Routing shall be possible with this. Take a look around. You will find something.

**Comment by KeenWarrior** [comment]
Try this https://www.npmjs.com/package/react-swipeable-routes

**Comment by ADRE9** [comment]
Sure I am on it! Thanks for the lead. I'll follow.

**Comment by ADRE9** [comment]
I have a doubt @KeenWarrior the MainLayout intstead of being used once why as it wrapping every view? Was there any specific reason behind that? Since for every Page it is using same component. It's redundant.

**Comment by Abhishek-kumar09** [comment]
`MainLayout` is a layout, it is wrapped around various views to put those views under a layout.

If it is something that is hidering you from creating swipeable views, then we can think of some workaround.

**Comment by ADRE9** [comment]
Yes actuall y the react-swipeable-routes has been integrated and works perfectly after I removed the MainLayout ,since you are using Switch so at any give time there's only one page showing so wrapping the MainLayout around the switch does the job. It introduces one problem though that the bottom navigation doesn't update according to the page.

**Comment by rizwan2000rm** [comment]
@KeenWarrior @ADRE9  Also we might need to test this properly on mobile devices. This may hinder with gestures in full screen mode which most of mobile devices use. It would really be annoying If somebody wants to go back but instead it changes routes. A work around I can think of is wrap swipeable routes to only navigation bar or leave the certain width from edges if using the whole viewport height.

**Comment by ADRE9** [comment]
Yes @rizwan2000rm  you are absolutely right. We need to first integrate and then test and improvise. We need to be careful so as not to create ambiguity in navigation. 

@Abhishek-kumar09 can I make a PR for integrating the Swipeable routes and then create another issue to update the bottom navigation according to the page?

**Comment by Abhishek-kumar09** [comment]
> @Abhishek-kumar09 can I make a PR for integrating the Swipeable routes and then create another issue to update the bottom navigation according to the page?

Sure, go on. We will see the rest during the implementation.

**Comment by ADRE9** [comment]
Okay before pulling I would like to discuss all the changes I've made in the structure. @Abhishek-kumar09 @KeenWarrior 
1.I removed the Switch component as ReactSwipeable was doing the same thing either way.
2. I removed out the MainLayout component from every page since it was unnecessary and redundant.
3. I added the MainLayout over the ReactSwipeable component.
4. I had to use useEffect to update location as the user swipes so as the location reflects in the Bottom Navigation.

**Comment by ADRE9** [comment]
@Abhishek-kumar09 its still has the tag of discussion-ongoing. Can you please make it as approved, please. And thank you so much for guiding me through and rectifying my bugs . This was my first major PR , although I have much experience with react , I had never worked in a team before. Thanks for being patient and guiding me. I'm learning loads from my mistakes and your guidance.

**Comment by Abhishek-kumar09** [comment]
Thanks for kind words @ADRE9
