### ISSUE TITLE
Create schedule view for course page

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/edu-client#4]
Part 2 of #2 

![image](https://user-images.githubusercontent.com/48255244/110600227-b5885900-81a9-11eb-8a8a-28ab578aedf3.png)

Please see the parent issue for full design and more information.

**Comment by faisaljamil25** [comment]
Can I work on this issue @Abhishek-kumar09 ?

**Comment by Ruchip16** [comment]
Can I work on this issue @Abhishek-kumar09 ?

**Comment by Ruchip16** [comment]
I would like to work on this issue @Abhishek-kumar09

**Comment by SankhaChak** [comment]
Hey @Abhishek-kumar09 , I would love to work on this issue.

**Comment by SankhaChak** [comment]
Thanks @Abhishek-kumar09 , looking up to the upcoming issues 😀
