### ISSUE TITLE
The footer of the web page is not directing to the respective pages.

### ISSUE THREAD

**Issue by Nis-chal-Jain** [codeforcauseorg/edu-client#406]
### Describe The Bug
In the end of the web page the social media icons and the Explore, about and the community all are not redirecting us to the respective sites when clicked upon it.

### How to reproduce.

- Open the website .
- Go to the end of the web page.
- Try to select the social media icons/ redirecting links of footer.

### Expected Behavior 
  Redirect to their respective sites

### Screenshots
![Edu Client and 2 more pages - Personal - Microsoft​ Edge 10-09-2021 14_29_30](https://user-images.githubusercontent.com/89198650/132831645-f9a9a9b5-2dba-4eab-b476-a30fda380341.png)

**Comment by Abhijay007** [comment]
can I work on this issue?

**Comment by Sarthak-06** [comment]
Is anyone working on this issue??

**Comment by Nis-chal-Jain** [comment]
> Is anyone working on this issue??

No

**Comment by yogitasaini** [comment]
Can I work on this issue
