### ISSUE TITLE
Myclasses / Moreoption crash

### ISSUE THREAD

**Issue by harshshaw** [codeforcauseorg/edu-client#45]
## Describe the bug
In myclasses section when we click on More option the page has no return button or no info available due to this we have to reload the page again 

## To Reproduce
1. Check for issue
2. Introduce some info
3. Make a redirecting route to Myclass when clicked on back button

## Before clicking More options
![Screenshot (85)](https://user-images.githubusercontent.com/51969606/110907335-3e7ecc00-8333-11eb-9075-252e0da507d4.png)
##After Clicking More options
![Screenshot (86)](https://user-images.githubusercontent.com/51969606/110907409-59e9d700-8333-11eb-8bd5-03ab98a17057.png)

**Comment by Siddhant-K-code** [comment]
What will be your approach to fix this?

**Comment by harshshaw** [comment]
Right now the value rendered in tabpanel is zero 

## Code 
export default function CoursePageViewWithVideo() {
  const classes = useStyles();
  const [value, setValue] = React.useState(0);

  const handleChange = (event, newValue) => {
    setValue(newValue);
  };

so we should render some value to Moreoptions since we have a handlechange method but it doesnt seem to work correctly for Moreoption tab

**Comment by harshshaw** [comment]
@Siddhant-K-code @KeenWarrior @kunal-kushwaha  please look into this

**Comment by Abhishek-kumar09** [comment]
Hi @harshshaw , the app majorly focuses on mobile view.

It was the problem with the bottom navbar which was fixed, please pull the latest code from the main repo. And verify if it still exist.

Feel free to open a new issue or current one, if you come out with some new problems.
I am closing it for now.
