### ISSUE TITLE
Profile Page not made [Static]

### ISSUE THREAD

**Issue by ArchishmanSengupta** [codeforcauseorg/edu-client#46]
## Describe the bug
The Profile Page is not made
![issue3](https://user-images.githubusercontent.com/71402528/110910904-f7dfa080-8337-11eb-8468-992ab5549641.png)

## To Reproduce
1.  Inserting Card-Profile Feature:

- UserName
- email
- courses on going
- payment details
- DOB(age restriction according to policies)

You can assign me this task!

**Comment by nitinosiris** [comment]
@ArchishmanSengupta are you working on it?

**Comment by ArchishmanSengupta** [comment]
on my forked repo yes, waiting for @kunal-kushwaha / @Abhishek-kumar09 to assign me this

**Comment by nitinosiris** [comment]
okk

**Comment by Abhishek-kumar09** [comment]
@ArchishmanSengupta I will be sharing you the profile page design once completed. Thanks for opening th e issue.

**Comment by ArchishmanSengupta** [comment]
@Abhishek-kumar09 okay

**Comment by helloCodingEra** [comment]
@Abhishek-kumar09 I m very new here (no contribution  yet) can i work on this issue ??

**Comment by NishcheyBhutani** [comment]
@Abhishek-kumar09 could u pls assign this to me if no one's Working on it?

**Comment by adarsh-technocrat** [comment]
> @ArchishmanSengupta I will be sharing you the profile page design once completed. Thanks for opening th e issue.

Hey, @Abhishek-kumar09  just curious to know about the design for the profile page as I have created some of the designs for application #122  would love to work on this too.

**Comment by ArchishmanSengupta** [comment]
hi @adarsh-technocrat i saw your UI designs. They look great. Maybe after getting the designs we can work on this together.

**Comment by ampsteric** [comment]
@kunal-kushwaha @KeenWarrior @Abhishek-kumar09 can i work on this issue?

**Comment by Abhijay007** [comment]
@ArchishmanSengupta I think this issue is already resolved you can close it now :)
