### ISSUE TITLE
Create Upcoming section in Home

### ISSUE THREAD

**Issue by rajatgupta24** [codeforcauseorg/edu-client#47]
## Create a new section in home
We should show some upcoming events or course in home.

We can create a new section under the "continue learning".

**Comment by himanshu211raj** [comment]
@KeenWarrior @kunal-kushwaha @Abhishek-kumar09 can i work on this section?

**Comment by Abhishek-kumar09** [comment]
![Android - 8](https://user-images.githubusercontent.com/48255244/110930034-a2fb5480-834e-11eb-8a29-784afdbeec31.png)
This is the initial homepage design Where are you planning to add upcoming courses? 
If you want to suggest design changes, and add more, you are welcome for that.

**Comment by himanshu211raj** [comment]
@Abhishek-kumar09 Above continue learning

**Comment by rajatgupta24** [comment]
Hi @Abhishek-kumar09, 
I think this design is almost same of what I'm thinking of,
Is someone currently working on this or can I contribute here.
Thanks

**Comment by RohankumarM** [comment]
We could elaborate on the idea of the homepage. 

The containers can be in the following order: 

1. Recommended Courses
2. Top Courses
3. Upcoming Courses

All these should

**Comment by rajatgupta24** [comment]
Hi @KeenWarrior, is somebody currently working on the Home page, can I be of some help.

**Comment by Abhishek-kumar09** [comment]
@RohankumarM it looks good.

**Comment by Abhishek-kumar09** [comment]
Who is working on it?

**Comment by RohankumarM** [comment]
Thanks @Abhishek-kumar09. If no one is working, I could probably start today.

**Comment by rajatgupta24** [comment]
@Abhishek-kumar09  I'd like to work on this, @RohankumarM we can work on this together.

**Comment by RohankumarM** [comment]
Any updates @rajatgupta24 ?

**Comment by rajatgupta24** [comment]
> Any updates @rajatgupta24 ?

Hi @RohankumarM,
Yeah I create the search bar and working on horizontal scroll, then I think I'll add cards (courses).
What you say?
