### ISSUE TITLE
Create Course Card components for Course Page

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/edu-client#5]
Part 3 of #2 

The component screenshot:
![image](https://user-images.githubusercontent.com/48255244/110600787-524af680-81aa-11eb-9fc0-5c087ed716d2.png)

Please see the parent issue for more details and full design

**Comment by rizwan2000rm** [comment]
I would like to work on this issue.

**Comment by Ruchip16** [comment]
@Abhishek-kumar09 Can I work on this issue ?

**Comment by harshshaw** [comment]
can i get assigned for this as well?
@KeenWarrior

**Comment by Abhishek-kumar09** [comment]
One person is enough for solving the issue, We will be creating  newer issues very soon
