### ISSUE TITLE
Fix some small mistakes in the README and add some hyperlinks

### ISSUE THREAD

**Issue by aflah02** [codeforcauseorg/edu-client#50]
In the README there are some minor mistakes such as spelling or grammar which I can fix.
Secondly I propose adding links for the technologies being used so people can access them quickly.
I can work on this

**Comment by aflah02** [comment]
Oh sorry forgot to tag
@KeenWarrior @kunal-kushwaha

**Comment by kunal-kushwaha** [comment]
@aflah02 Go for it, could you also maybe move the section from [here](https://github.com/codeforcauseorg/edu-client#-setting-up-locale-environment) till [here](https://github.com/codeforcauseorg/edu-client#-creating-a-pull-request) in the CONTRIBUTING.md file?

**Comment by aflah02** [comment]
@kunal-kushwaha yeah sure i'll do that

**Comment by aflah02** [comment]
@kunal-kushwaha I've done this thrice already it works and then some other requests get merged and a conflict ensues.

**Comment by Deveshb15** [comment]
Can I work on this?

**Comment by Deveshb15** [comment]
@kunal-kushwaha can I work on this?

**Comment by Abhijay007** [comment]
@aflah02 this issue is resolved from PR(#118) you can close it now :)
