### ISSUE TITLE
Add Credits Section in README.md for contributors

### ISSUE THREAD

**Issue by kunal-kushwaha** [codeforcauseorg/edu-client#51]
Have a credits section in our `README.md` file like [this](https://github.com/facebook/jest#credits) to recognise contributors in the project.

**Comment by Harshal0902** [comment]
@kunal-kushwaha can I work on this issue?

**Comment by kunal-kushwaha** [comment]
@Harshal0902 Go for it!

**Comment by harshshaw** [comment]
@kunal-kushwaha please consider me for upcoming issues also i have raised a few

**Comment by symaticvisuals** [comment]
@kunal-kushwaha I also want to work on this issue. Can I?

**Comment by rajdeep-ghosh** [comment]
@kunal-kushwaha I would like to work on this issue
