### ISSUE TITLE
Adding tags to Readme.md file

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [codeforcauseorg/edu-client#54]
## Problem faced
The Readme file still lacks some information. The short information will let the user / contributors get a quick glance of the projec.

## Describe the solution you'd like
Adding shield.io tags will help the Readme File to me more specific for users

**Comment by kaiwalyakoparkar** [comment]
Please assign this issue to me so that I can start working on it!

**Comment by ArchishmanSengupta** [comment]
suggestion: you can also add screenshots of the website(figma design)

**Comment by kaiwalyakoparkar** [comment]
> suggestion: you can also add screenshots of the website(figma design)

Yeah but those screenshots will obviously with the admin so...

**Comment by ArchishmanSengupta** [comment]
> > suggestion: you can also add screenshots of the website(figma design)
> 
> Yeah but those screenshots will obviously with the admin so...

You can always ask. I think they will provide you

**Comment by kaiwalyakoparkar** [comment]
Yeah sure. @KeenWarrior & @kunal-kushwaha could jive more valuable insights on this

**Comment by kaiwalyakoparkar** [comment]
@KeenWarrior / @kunal-kushwaha please assign this issue to me

**Comment by Abhishek-kumar09** [comment]
Hi @kaiwalyakoparkar, could you explain what are the informations that the current readme is lacking and you can add.

**Comment by kaiwalyakoparkar** [comment]
Hi @Abhishek-kumar09, I am thinking about adding https://shields.io/ tags that will give an insight into the project to the user at a glance. Like building, languages, version, no of forks, no of stars, open PR's, social accounts, code coverage, analysis, chat, etc. You can check all the fields from the link above.

**Comment by Abhishek-kumar09** [comment]
That's a good idea

**Comment by kaiwalyakoparkar** [comment]
I'll start working on it !
