### ISSUE TITLE
refractor:prettify all the files of the repo

### ISSUE THREAD

**Issue by abhishekkumar08** [codeforcauseorg/edu-client#55]
## Description
The repo contains many eslint and prettier errors, the command ```npm run format``` prettified all the files. I'm hoping to solve all the eslint errors.
Should I make a PR for this?
The files affected after prettifying were:
```
        modified:   .eslintrc.json
        modified:   .github/ISSUE_TEMPLATE/bug_report.md
        modified:   .github/ISSUE_TEMPLATE/feature_request.md
        modified:   .github/feature_request_template.md
        modified:   .github/pull_request_template.md
        modified:   CODE_OF_CONDUCT.md
        modified:   CONTRIBUTING.md
        modified:   README.md
        modified:   android/app/src/main/assets/capacitor.config.json
        modified:   capacitor.config.json
        modified:   package-lock.json
        modified:   package.json
        modified:   public/manifest.json
        modified:   src/App.js
        modified:   src/App.test.js
        modified:   src/Routes.js
        modified:   src/actions/accountActions.js
        modified:   src/components/Button/ButtonComponent.js
        modified:   src/components/auth/Auth.js
        modified:   src/components/courseCard/courseCard1.js
        modified:   src/components/courseDetails/schedule.js
        modified:   src/components/courseDetails/scheduleDetails.js
        modified:   src/components/wishlistCard/index.js
        modified:   src/config/index.js
        modified:   src/constants/index.js
        modified:   src/context/SettingsContext.js
        modified:   src/index.js
        modified:   src/layouts/MainLayout/BottomNav.js
        modified:   src/layouts/MainLayout/TopBar/Account.js
        modified:   src/layouts/MainLayout/TopBar/HeaderItems.js
        modified:   src/layouts/MainLayout/TopBar/Item.js
        modified:   src/layouts/MainLayout/TopBar/index.js
        modified:   src/layouts/MainLayout/index.js
        modified:   src/pages/CoursePageViewWithVideo/index.js
        modified:   src/pages/HomePage.js
        modified:   src/pages/HomeView/Hero.js
        modified:   src/pages/HomeView/NonHero.js
        modified:   src/pages/HomeView/index.js
        modified:   src/pages/PersonalPage.js
        modified:   src/pages/ProfilePage.js
        modified:   src/pages/WishlistPage.js
        modified:   src/pages/wishListView/index.js
        modified:   src/reducers/accountReducer.js
        modified:   src/reducers/index.js
        modified:   src/reportWebVitals.js
        modified:   src/services/authService.js
        modified:   src/setupTests.js
        modified:   src/store/index.js
        modified:   src/theme/index.js
        modified:   src/theme/shadows.js
        modified:   src/theme/typography.js
        modified:   src/utils/analytics.js
        modified:   src/utils/axios.js
        modified:   src/utils/bytesToSize.js
        modified:   src/utils/getInitials.js
        modified:   src/utils/settings.js
        modified:   src/utils/wait.js
```

**Comment by Abhishek-kumar09** [comment]
Hey, @abhishekkumar08 
We can better add prettier to the repo: https://www.npmjs.com/package/prettier
So whenever w e will run npm run format, It will automatically format the whole code. 
We had already integrated prettier in codeforcause/codeforcause repo. You can have a look there.

**Comment by Siddhant-K-code** [comment]
was saying the same in #17

**Comment by abhishekkumar08** [comment]
> 
> 
> Hey, @abhishekkumar08
> We can better add prettier to the repo: https://www.npmjs.com/package/prettier
> So whenever w e will run npm run format, It will automatically format the whole code.
> We had already integrated prettier in codeforcause/codeforcause repo. You can have a look there.

It's already there in this repo also, I only ran the command, seems like no one has used it till now. So asking to create a PR for the same.

**Comment by Abhishek-kumar09** [comment]
> was saying the same in #17

Yes look like he created the PR and didn't ran it.

@abhishekkumar08 You can create a PR for the same.

**Comment by faisaljamil25** [comment]
> > was saying the same in #17
> 
> Yes look like he created the PR and didn't ran it.
> 
> @abhishekkumar08 You can create a PR for the same.

Actually, there were some issues running lint that's why I did not run it. I was waiting for any maintainer's reply for the same. Now since @abhishekkumar08 has run it which solved most of the issues, still there are some issues that need to be sorted. I have also solved some of them but some errors required your guide to solve. I am creating a PR #61  for the eslint errors which I have already solved. Most of the remaining errors are related to props-validation. @Abhishek-kumar09 @Siddhant-K-code can you look into it and let me know what should I do further.

![Screenshot 2021-03-12 180126](https://user-images.githubusercontent.com/69186619/110940603-30de3c00-835d-11eb-9581-3dad84abe558.png)
