### ISSUE TITLE
Add splash screen inside Android/iOS Application.

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/edu-client#56]
## What is feature
We want to have a splash screen for the ionic aplication when opened in android or iOS.

## Describe the solution you'd like
Adding splash screen, requires a bit of ionic/ capacitor knowledge: 
https://ionicframework.com/docs/native/splash-screen
.

**Comment by himanshu211raj** [comment]
can i add a splash screen using flutter? @Abhishek-kumar09

**Comment by Abhishek-kumar09** [comment]
How would you integrate flutter inside ionic application, I don't think there is some ways of doing that if I am not wrong, flutter is framework cum sdk and requires its own seperate environment for building and running cross platform applications.

**Comment by himanshu211raj** [comment]
> How would you integrate flutter inside ionic application, I don't think there is some ways of doing that if I am not wrong, flutter is framework cum sdk and requires its own seperate environment for building and running cross platform applications.

sorry i got some misconception.

**Comment by Abhishek-kumar09** [comment]
No problem, thanks for showing your interest.

**Comment by Striver08** [comment]
I would like to work on this issue, Can you please ellaborate it a bit

**Comment by Striver08** [comment]
@Abhishek-kumar09 Can you assign it to me.

**Comment by Abhishek-kumar09** [comment]
> I would like to work on this issue, Can you please ellaborate it a bit

Splash screens are screens that shows up when someone app is just starting and the app has not finished loading. Like you see in any android application.

You have to add a splash screen for this application too.
You can refer: https://ionicframework.com/docs/native/splash-screen
or may also watch some youtube videos demonstrating it.

**Comment by Striver08** [comment]
> > I would like to work on this issue, Can you please ellaborate it a bit
> 
> Splash screens are screens that shows up when someone app is just starting and the app has not finished loading. Like you see in any android application.
> 
> You have to add a splash screen for this application too.
> You can refer: https://ionicframework.com/docs/native/splash-screen
> or may also watch some youtube videos demonstrating it.

Thanks a lot, I'll do it. @Abhishek-kumar09

**Comment by Abhishek-kumar09** [comment]
@Striver08 Are you working on it?

**Comment by rizwan2000rm** [comment]
I would love to take this up!

**Comment by Abhishek-kumar09** [comment]
Okay, 
Here is the more description: https://github.com/codeforcauseorg/edu-client/issues/56#issuecomment-798275707
you have to run your app in the android device itself, to test the changes.

**Comment by rizwan2000rm** [comment]
@Abhishek-kumar09 Do we have the assets for static splash image and app icons ?
I was thinking we can add a loading animation after we splash a static image.

**Comment by Abhishek-kumar09** [comment]
For now add splash with any any dummy image and text.

**Comment by rizwan2000rm** [comment]
@Abhishek-kumar09 Update: Here is what splash screen looks like. Should I proceed with a PR ?


https://user-images.githubusercontent.com/48753482/113828233-cb397000-97a1-11eb-8a38-c131d7c42719.mp4

**Comment by Abhishek-kumar09** [comment]
> Should I proceed with a PR ?

Yes please, it looks good. we can modify that in future if needed.
