### ISSUE TITLE
Issues with lock files.

### ISSUE THREAD

**Issue by rizwan2000rm** [codeforcauseorg/edu-client#59]
## Describe the bug

Some people are using npm and some are using yarn. I think it is not recommend to have both lock files. They could have sync issues. I looked into it to find a better mix yarn/npm experience.

## Possible Solution

I think we could use yarn import to have a smooth mixed npm/yarn environments.
https://classic.yarnpkg.com/blog/2018/06/04/yarn-import-package-lock/
https://classic.yarnpkg.com/en/docs/cli/import/

**Comment by Jeevan-Kiran-Lenka** [comment]
Can I work on it?

**Comment by Abhishek-kumar09** [comment]
Good catch @rizwan2000rm 
I guess https://github.com/codeforcauseorg/edu-client/pull/76 will solve the issue, so from now  yarn's lock file will be ignored by github. Still we need npm lock file for deployement and github actions so didn't removed that.

Sorry I saw your comment late @Jeevan-Kiran-Lenka.

**Comment by Jeevan-Kiran-Lenka** [comment]
No issues @Abhishek-kumar09

**Comment by rizwan2000rm** [comment]
@Abhishek-kumar09 Yeah that would fix it. Closing this issue.
