### ISSUE TITLE
Create a pull request Template

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/edu-client#6]
Create a pull request that covers all the requirements for A perfect Pull request and is not limited to:
- Perfect code style check
- successful build
- No console errors
- No console warnings (sometimes)
- Pull request against branch name
- responsive UI
- Test case being passed

**Comment by Abhishek-kumar09** [comment]
Go ahead, thanks for your interest.

**Comment by Siddhant-K-code** [comment]
we didn't have `Code_of_Conduct.md` or `Contributing.md` ?
