### ISSUE TITLE
Adding a step of npm install in readme.md

### ISSUE THREAD

**Issue by Jeevan-Kiran-Lenka** [codeforcauseorg/edu-client#62]
As I was setting my dev environment, I followed up the procedure that was given in the documentation apparently the command of `npm install`  or `npm install -g npm-install-missing` is missing, adding that step will help newcomers to set up the dev environment easily and quickly, and also can check the project in deployment mode

**Comment by Jeevan-Kiran-Lenka** [comment]
I would like to work on this issue

**Comment by kaiwalyakoparkar** [comment]
From next time please don't pull a request on any issue without getting assigned to it

**Comment by Jeevan-Kiran-Lenka** [comment]
I asked the maintainers to review the issue yesterday, but then the newcomers were getting an error on error due to this single line therefore I PR'ed
