### ISSUE TITLE
Create a .env file to store config keys

### ISSUE THREAD

**Issue by Anurag5086** [codeforcauseorg/edu-client#79]
Create a .env file to store config keys of firebase auth.

**Comment by Anurag5086** [comment]
@Abhishek-kumar09 @KeenWarrior @kunal-kushwaha  Please assign it to me. I would like to work on this.

**Comment by kaiwalyakoparkar** [comment]
But what would you add to it? Or you will make a pr just by adding a .env file?

**Comment by Anurag5086** [comment]
Sure. Thanks. @Abhishek-kumar09

**Comment by Anurag5086** [comment]
@Abhishek-kumar09 please check my PR for this issue. #97
