### ISSUE TITLE
Need Help! - Not able to run project locally

### ISSUE THREAD

**Issue by SUSHANT731** [codeforcauseorg/edu-client#8]
Command "start" not found.
after running the command yarn start

**Comment by rizwan2000rm** [comment]
Hey @SUSHANT731 did you install the dependencies for the project ??
You might need to run "yarn" in your root directory to get all dependencies and then you can run "yarn start" to run the project.

**Comment by Ruchip16** [comment]
@SUSHANT731  I think maybe you haven't install yar package that's y it is showing

**Comment by SUSHANT731** [comment]
@rizwan2000rm @Ruchip16  I have insatall the yarn package in the root terminal and then executed the yarn start command what are the other dependencies required??

**Comment by SUSHANT731** [comment]
Can anyone share a video for the same that would be helpful??

**Comment by ritvij14** [comment]
@SUSHANT731 first do `yarn install` and then do `yarn start`. It should work then.

**Comment by Abhishek-kumar09** [comment]
Most probably you may be using npm.
So instaed of doing yarn start, you can run 
```
npm install
npm start
```

Otherwise if you would like to work with yarn itself,
do: 
```
npm install -g yarn
yarn
yarn start
```
