### ISSUE TITLE
Bottom Navigation doesn't update according to the page.

### ISSUE THREAD

**Issue by ADRE9** [codeforcauseorg/edu-client#83]
## Describe the bug
The bottom navigation for the website doesn't update according to the page.

## To Reproduce

1.useEffect hook to update the value of the navigation each time according to the location will keep it updated.

## Expected behavior
The Navigation will update each time the page changes.

## Environment (please complete the following information):

- OS: Windows
- Browser: Edge

https://user-images.githubusercontent.com/49809895/111045102-63c62400-8472-11eb-9449-8ee11e56aa82.mp4

**Comment by ADRE9** [comment]
@kunal-kushwaha @Abhishek-kumar09  can I work on this issue?

**Comment by rizwan2000rm** [comment]
@ADRE9 I think this issue has been fixed with d6908d91447b37582f99383772175ebc62809e68

**Comment by rajatgupta24** [comment]
If this issue is resolved, please close it.

**Comment by ADRE9** [comment]
Yes , I created this issue yesterday and @KeenWarrior  has solved it today. So thanks @rizwan2000rm for pointing it out.
