### ISSUE TITLE
Add favicon and title to the react app.

### ISSUE THREAD

**Issue by Abhijay007** [codeforcauseorg/edu-client#84]
Currently, the edu-client react app has official `react logo` as a favicon and `react app` as a title.  Edit that to CFC- codeForCause official logo (shown below in "after" snip from the official site)and change the title to codeForCause-edu.

***before*** 

![react-fav](https://user-images.githubusercontent.com/64387054/111061146-dad9d780-84c7-11eb-91f4-c850d63c11ba.PNG)

***after***
![cfc-fav](https://user-images.githubusercontent.com/64387054/111061147-dca39b00-84c7-11eb-9d0f-c6a78a2a605a.PNG)

**Comment by Abhijay007** [comment]
@KeenWarrior @Abhishek-kumar09 sir can I implement this?

**Comment by Abhishek-kumar09** [comment]
We will be running this application in android and iOS application, so we may not be needing those since making appIcon and splash screens would cover those parts. Still if you want you can work on it.
For now change the name to educause :)

**Comment by Abhishek-kumar09** [comment]
We will be needing a new icons/favicon too maybe we can halt this issue for now.

**Comment by Abhijay007** [comment]
> We will be needing a new icons/favicon too maybe we can halt this issue for now.

ok, No problem sir, close it for now, I will try to contribute to other parts of the project :)

**Comment by Abhishek-kumar09** [comment]
Thanks for raising the issue, I will tag you to complete this part once we have required assets.
I am closing it for now.
