### ISSUE TITLE
Remove all errors from development console

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/edu-client#88]
**Describe the bug**
Application has  a lots of console errors on the browser console window. We can fix it by doing some minor tweaks in code style.

## To Reproduce

1. Start the application with npm run start
2. Head over to console window once application is live on localhost
3. These are the errors and warnings we can get rid of.

## Expected behavior

There should 0 errors in the console.

## Environment (please complete the following information):

- OS: Ubuntu
- Browser: google-chrome-stable

**Comment by rizwan2000rm** [comment]
I would like to work on this issue.
