### ISSUE TITLE
Add navbar with static pages 

### ISSUE THREAD

**Issue by Abhijay007** [codeforcauseorg/edu-client#89]
## Is your feature request related to a problem? Please describe.

currently, there is no navbar on the top of the application for the web app and android app of the project. we can add a navbar with logo and link to static pages like about us, contact, etc.

***screenshots***

web app
![no_nav](https://user-images.githubusercontent.com/64387054/111066881-526b2f00-84e7-11eb-9e44-870d306b9da1.PNG)

Android through chrome inspect
![mobile_nav](https://user-images.githubusercontent.com/64387054/111066941-ac6bf480-84e7-11eb-99ee-27c2eda8b855.PNG)

## Describe the solution you'd like

make a new navbar/header component and use that for all pages.

**Comment by Abhijay007** [comment]
@KeenWarrior @Abhishek-kumar09 can I work on this?

**Comment by Abhishek-kumar09** [comment]
@Abhijay007 The app is more for mobile, We can add some web functionalities once the mobile 1st version is completed. I guess bottomnavbar will suffice all the requirements for mobile screens.

There will be some screens which will not be having bottomnavabar, there we would be adding topbar.

The topbar's code is already here: https://github.com/codeforcauseorg/edu-client/tree/main/src/layouts/MainLayout/TopBar

It needs only alterations adhering to the currenting application needs.

**Comment by Abhijay007** [comment]
> @Abhijay007 The app is more for mobile, We can add some web functionalities once the mobile 1st version is completed. I guess bottomnavbar will suffice all the requirements for mobile screens.
> 
> There will be some screens which will not be having bottomnavabar, there we would be adding topbar.
> 
> The topbar's code is already here: https://github.com/codeforcauseorg/edu-client/tree/main/src/layouts/MainLayout/TopBar
> 
> It needs only alterations adhering to the currenting application needs.

ok, no problem, and thanks for letting me know about it. I will try to focus more on the mobile version from now and try to contribute to that. you can close this issue.

**Comment by Abhishek-kumar09** [comment]
Thanks @Abhijay007 , We will be first completing the mobile view because the motive is to create a cross platform hybrid application with capacitor, once done will be focusing on adding some extra features to make it compatible for Web versions too.

Thanks for opening the issue.
