### ISSUE TITLE
[Feature Update] Adding a Search bar with Explore Courses DROPdown button instead of Courses

### ISSUE THREAD

**Issue by ArchishmanSengupta** [codeforcauseorg/edu-client#9]
![issue1](https://user-images.githubusercontent.com/71402528/110690375-ded8d180-8209-11eb-94a7-98009d261c74.png)

I propose to add a Extensive ```search bar``` consisting of the logo at the left side of the ``Explore DROPdown button.``

# The Explore Button will include all the necessary things inside it like:
1. Goals
2. Subjects
3. Personal Statistics (preferably integration with WAKATIME)
4. [Extra features soon] 

# Why using the Left side approach will fetch more users?
## here's why : [Click ME](https://www.nngroup.com/articles/horizontal-attention-leans-left/)

According to UX Research:- Web users spend 80% of their time viewing the left half of the page and 20% viewing the right half. Adhering to design conventions will help maximize users’ efficiency and company profits.

Please Assign me this job so that i can work on this asap!

Thank you,
Archie

**Comment by avinash14022002** [comment]
Wanted to work.

**Comment by ArchishmanSengupta** [comment]
@Siddhant-K-code please assign me the task

**Comment by Siddhant-K-code** [comment]
Only Maintainers Can Assign!

**Comment by ArchishmanSengupta** [comment]
@KeenWarrior please assign me the task

**Comment by ArchishmanSengupta** [comment]
@KeenWarrior please assign me this

**Comment by Abhishek-kumar09** [comment]
On which page you are planning to add this?

**Comment by Siddhant-K-code** [comment]
> On which page you are planning to add this?

I think, on Home Page

**Comment by ArchishmanSengupta** [comment]
> On which page you are planning to add this?

yes home page

**Comment by ArchishmanSengupta** [comment]
@Abhishek-kumar09 bhaiya will the nav bar be in bottom permanently?

**Comment by Abhishek-kumar09** [comment]
> > On which page you are planning to add this?
> 
> I think, on Home Page

![image](https://user-images.githubusercontent.com/48255244/111072842-5e181f00-8502-11eb-9ba1-578105c5205e.png)

Homepage has already a search bar designed.

**Comment by Abhishek-kumar09** [comment]
> @Abhishek-kumar09 bhaiya will the nav bar be in bottom permanently?

Yes, ideally it should be

**Comment by ArchishmanSengupta** [comment]
> > > On which page you are planning to add this?
> > 
> > 
> > I think, on Home Page
> 
> ![image](https://user-images.githubusercontent.com/48255244/111072842-5e181f00-8502-11eb-9ba1-578105c5205e.png)
> 
> Homepage has already a search bar designed.

Then i can make that in the wishlist section

**Comment by Abhijay007** [comment]
@ArchishmanSengupta we are working on a new UI design in which the wishlist section is based on a different approach which may not contain any search bar I think yo can close this issue for now :)
