### ISSUE TITLE
Add shadow to navbar

### ISSUE THREAD

**Issue by rajatgupta24** [codeforcauseorg/edu-client#90]
I think we should add some shadow to the top of the bottom-navbar.
![image](https://user-images.githubusercontent.com/55191777/111067824-f2c35280-84eb-11eb-9e04-9a8d6b0246e2.png)

**Comment by poojadas07** [comment]
I want to work on this issue. @Abhishek-kumar09  Can you please assign this issue to me?

**Comment by Abhishek-kumar09** [comment]
Please go on

**Comment by poojadas07** [comment]
![Capture](https://user-images.githubusercontent.com/66192403/111401965-54eca500-86f0-11eb-9afb-de022b1fc656.PNG)
Now it is looking like this. @Abhishek-kumar09 please have a look.
