### ISSUE TITLE
Create the Landing Page .

### ISSUE THREAD

**Issue by ADRE9** [codeforcauseorg/edu-client#93]
## Is your feature request related to a problem? Please describe.
Create a Landing page with the option of Sign in With Google properly implemented.

## Describe the solution you'd like
Create a beautiful landing page that has the option of Sign In With Google

**Comment by ADRE9** [comment]
@Abhishek-kumar09 Is there any file that shows how exactly the landing page should look? If yes, can I work on this issue?

**Comment by Abhishek-kumar09** [comment]
A dummy login page is already there that supports sign In with google. We are currently only accepting  google sign-in.

**Comment by ADRE9** [comment]
Yes I saw, So is there no plan to enhance it? If you have any ideas can you please share, I can work on it.

**Comment by Abhishek-kumar09** [comment]
It definately needs a lot of enhancement.
@ADRE9 Have you worked with figma before?

Can you share your design.

Or if you have not worked with figma, you can implement this design too, will make the more enhancement on top of it if needed. Please always make design that adheres to current app theme.

**Comment by ADRE9** [comment]
Yes I have good experience with both Figma and Adobe. I was thinking of making a glassmorphism design bit it won't match the overall app theme. Can you give me a day to sort out a good design and I'll share the link to figma. If you agree I can start working on it. @Abhishek-kumar09

**Comment by Abhishek-kumar09** [comment]
> If you agree I can start working on it.

Yes, please. We can make the design of landing page first.

**Comment by ADRE9** [comment]
![iPhone X-XS-11 Pro – 1](https://user-images.githubusercontent.com/49809895/111294776-aa816d00-8670-11eb-8b78-538cfdfa48df.png)

I have made this design for the mobile in Adobe XD. Any changes required @Abhishek-kumar09 ?

**Comment by Abhishek-kumar09** [comment]
Okay, that looks good.
the red variant would be: `#A60000` and blue variant we are using is `#150051`

I will add it in the theme too, but for now you can start your progress

**Comment by ADRE9** [comment]
Okay. I picked the indigo[600] color from the theme.js file only. And the red colour used is the Google Theme used for Google buttons. I'll change it to the colors you want and more enhancements we can add accordingly.

**Comment by ADRE9** [comment]
![Screenshot 2021-03-18 042321](https://user-images.githubusercontent.com/49809895/111549169-c20c4300-87a1-11eb-90be-419a87506c51.jpg)
@Abhishek-kumar09 I have added the neumorphic card to make it look more elegant. My previous PR of React Swipeable has not merged so my commits are added to the PR of React Swipeable Routes. Is there any more changes required?

**Comment by Abhishek-kumar09** [comment]
Fix is merged.
