### ISSUE TITLE
Bottom navbar get hidden when scrolled down.

### ISSUE THREAD

**Issue by Abhishek-kumar09** [codeforcauseorg/edu-client#95]
## Describe the bug

Bottom nanvbar is hidden when scrolled down to the limit
This bug may have introduced here: https://github.com/codeforcauseorg/edu-client/pull/63

## To Reproduce

1. Open application in development mode.
2. scroll down to bottom and bottom navabar will be disappeared once.

## Environment (please complete the following information):

- OS: Ubuntu
- Browser: Google chrome

**Comment by Abhijay007** [comment]
@Abhishek-kumar09 can I work on this?

**Comment by Abhishek-kumar09** [comment]
Sure go on. Let me know if need some help. You can also seek some help from @ADRE9.

**Comment by Abhijay007** [comment]
> Sure go on. Let me know if need some help. You can also seek some help from @ADRE9.

Ya sure. And Thanks for assigning this to me I will try my best order to solve this.
