### ISSUE TITLE
React Swipeable Routes also has Course Details Page

### ISSUE THREAD

**Issue by rizwan2000rm** [codeforcauseorg/edu-client#96]
## Describe the bug

I think React Swipeable Routes should not be wrapped around the Course Detail Page.
Once visiting the /course/:id route one can swipe beyond the Profile Page.

## To Reproduce

1. Visit /course/:id route once
2. Now you can swipe backwards and forwards from this page (i.e. swipe right from Profile Page to go to  Course Detail page and vice versa)

## Expected behavior

Course Details page should not be swipeable.

## Environment (please complete the following information):

- OS: Windows 10
- Browser: Firefox Nightly

## Additional context

This only happens once the Course Detail page render is triggered by going to the route. You cannot swipe to it unless you go to /course/:id route

**Comment by ADRE9** [comment]
@Abhishek-kumar09  can I work on it? It needs a small fix.

**Comment by Abhishek-kumar09** [comment]
Thanks @rizwan2000rm for opening this issue.

**Comment by ADRE9** [comment]
@Abhishek-kumar09 I have made the PR.
